/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.DocGiaBUS;
import DTO.DocGiaDTO;
import java.awt.Color;
import Util.ReColorIcon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class AddDocGiaForm extends javax.swing.JFrame {
    
    private ImageIcon icon = new ImageIcon(getClass().getResource("/icons/close.png"));
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddDocGiaForm.class.getName());

    /**
     * Creates new form AddDocGiaForm
     */
    public AddDocGiaForm() {
        setUndecorated(true);
        initComponents();
        setBackground(new java.awt.Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        this.pack();
        DocGiaBUS bus = new DocGiaBUS();
        madocgialabel.setText(bus.generateMADG());
        madocgialabel.setVisible(false);
        madocgiatext.setVisible(false);
        trangthaitext.setVisible(false);
        trangthailabel.setVisible(false);
        titlelabel.setText("Thêm độc giả");
    }
    public AddDocGiaForm(DocGiaDTO dg)
    {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        madocgialabel.setVisible(true);
        madocgiatext.setVisible(true);
        madocgiatext.setEnabled(false);
        trangthaitext.setVisible(true);
        trangthailabel.setVisible(true);
        titlelabel.setText("Sửa độc giả");
        madocgiatext.setText(dg.getMaDG());
        tendocgiatext.setText(dg.getTenDG());
        hodocgiatext.setText(dg.getHoDG());
        sdttext.setText(dg.getSDT());
        diachidocgiatext.setText(dg.getDiaChi());
        trangthaitext.setText(String.valueOf(dg.getTrangThai()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlelabel = new javax.swing.JLabel();
        hodocgialabel = new javax.swing.JLabel();
        diachilabel = new javax.swing.JLabel();
        huybutton = new javax.swing.JButton();
        xacnhanbutton = new javax.swing.JButton();
        hodocgiatext = new javax.swing.JTextField();
        tendocgialabel = new javax.swing.JLabel();
        sdttext = new javax.swing.JTextField();
        sdtlabel = new javax.swing.JLabel();
        tendocgiatext = new javax.swing.JTextField();
        diachidocgiatext = new javax.swing.JTextField();
        pnClose = new javax.swing.JPanel();
        closeIcon = new javax.swing.JLabel();
        madocgialabel = new javax.swing.JLabel();
        madocgiatext = new javax.swing.JTextField();
        trangthailabel = new javax.swing.JLabel();
        trangthaitext = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204), 3));

        titlelabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titlelabel.setText("Quản lý độc giả");

        hodocgialabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        hodocgialabel.setText("Họ độc giả");

        diachilabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        diachilabel.setText("Địa chỉ");

        huybutton.setBackground(new java.awt.Color(153, 153, 153));
        huybutton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        huybutton.setForeground(new java.awt.Color(255, 255, 255));
        huybutton.setText("Hủy");
        huybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                huybuttonMouseClicked(evt);
            }
        });
        huybutton.addActionListener(this::huybuttonActionPerformed);

        xacnhanbutton.setBackground(new java.awt.Color(0, 153, 102));
        xacnhanbutton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        xacnhanbutton.setForeground(new java.awt.Color(255, 255, 255));
        xacnhanbutton.setText("Xác Nhận");
   	xacnhanbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xacnhanbuttonMouseClicked(evt);
            }
        });
        xacnhanbutton.addActionListener(this::xacnhanbuttonActionPerformed);

        hodocgiatext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tendocgialabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tendocgialabel.setText("Tên độc giả");

        sdttext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        sdtlabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        sdtlabel.setText("SDT");

        tendocgiatext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        diachidocgiatext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diachidocgiatext.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        diachidocgiatext.addActionListener(this::diachidocgiatextActionPerformed);

        pnClose.setBackground(new java.awt.Color(255, 255, 255));
        pnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnCloseMouseExited(evt);
            }
        });

        closeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeIconMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnCloseLayout = new javax.swing.GroupLayout(pnClose);
        pnClose.setLayout(pnCloseLayout);
        pnCloseLayout.setHorizontalGroup(
            pnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeIcon)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        pnCloseLayout.setVerticalGroup(
            pnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        madocgialabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        madocgialabel.setText("Mã độc giả");

        madocgiatext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        madocgiatext.addActionListener(this::madocgiatextActionPerformed);

        trangthailabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        trangthailabel.setText("Trạng thái");

        trangthaitext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219)
                .addComponent(pnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hodocgialabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diachilabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tendocgialabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sdtlabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hodocgiatext, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sdttext, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tendocgiatext, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diachidocgiatext))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(madocgialabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addGap(25, 25, 25)
                                .addComponent(madocgiatext, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(trangthailabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(25, 25, 25)
                                .addComponent(trangthaitext, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(huybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(xacnhanbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(pnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(madocgialabel)
                        .addComponent(madocgiatext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hodocgialabel)
                        .addComponent(hodocgiatext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(trangthailabel)
                        .addComponent(trangthaitext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tendocgialabel)
                        .addComponent(tendocgiatext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdtlabel)
                    .addComponent(sdttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(diachilabel)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(diachidocgiatext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(huybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xacnhanbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    public void btnadd()
    {
        
    }
    
    private void huybuttonMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        this.dispose();
    }                                      

    private void huybuttonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        clearForm();
        setVisible(false);

    }                                         

    private void xacnhanbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        DocGiaBUS bus = new DocGiaBUS();
        String ttString = trangthaitext.getText().trim(); 
        
        DocGiaDTO dg;
         if (sdttext.getText().length()!=10)
        {
            JOptionPane.showMessageDialog(null, "Sai định dạng SDT");
            sdttext.requestFocus();
            return;
        }
        if (titlelabel.getText().equals("Thêm độc giả"))
        {
        dg = new DocGiaDTO(bus.generateMADG(),hodocgiatext.getText(),tendocgiatext.getText(),sdttext.getText(),diachidocgiatext.getText(),0);
        if (bus.addDocGia(dg))
        {
            JOptionPane.showMessageDialog(null, "thêm độc giả thành công");
        }
        clearForm();
        setVisible(false);
        }
        else
        {
            String ma = madocgiatext.getText();
            String ho = hodocgiatext.getText();
            String ten = tendocgiatext.getText();
            String sdt = sdttext.getText();
            String diachi = diachidocgiatext.getText();
            int trangThai = Integer.parseInt(ttString);
            dg = new DocGiaDTO(ma,ho,ten,sdt,diachi,trangThai);
            if (bus.updateDocGia(dg))
            {
            JOptionPane.showMessageDialog(null,"sửa thành công");
            }
        }
        // TODO add your handling code here:
        
    }                                             

    private void diachidocgiatextActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        this.dispose();
    }                                      

    private void closeIconMouseEntered(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        pnClose.setBackground(Color.red);
        closeIcon.setIcon(ReColorIcon.recolorIcon(icon, Color.WHITE));
    }                                      

    private void pnCloseMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        this.dispose();
    }                                    

    private void pnCloseMouseEntered(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        pnClose.setBackground(Color.red);
        closeIcon.setIcon(ReColorIcon.recolorIcon(icon, Color.WHITE));
    }                                    

    private void pnCloseMouseExited(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        pnClose.setBackground(Color.WHITE);
        closeIcon.setIcon(ReColorIcon.recolorIcon(icon, Color.BLACK));
    }                                   

    private void xacnhanbuttonMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void madocgiatextActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    public void clearForm() {
    hodocgiatext.setText("");
    tendocgiatext.setText("");
    sdttext.setText("");
    diachidocgiatext.setText("");
    }
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddDocGiaForm().setVisible(true));
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JLabel closeIcon;
    private javax.swing.JTextField diachidocgiatext;
    private javax.swing.JLabel diachilabel;
    private javax.swing.JLabel hodocgialabel;
    private javax.swing.JTextField hodocgiatext;
    private javax.swing.JButton huybutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel madocgialabel;
    private javax.swing.JTextField madocgiatext;
    private javax.swing.JPanel pnClose;
    private javax.swing.JLabel sdtlabel;
    private javax.swing.JTextField sdttext;
    private javax.swing.JLabel tendocgialabel;
    private javax.swing.JTextField tendocgiatext;
    private javax.swing.JLabel titlelabel;
    private javax.swing.JLabel trangthailabel;
    private javax.swing.JTextField trangthaitext;
    private javax.swing.JButton xacnhanbutton;
    // End of variables declaration                   
}
