/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.CTPhieuMuonBUS;
import BUS.CTPhieuNhapBUS;
import BUS.PhieuMuonBUS;
import BUS.PhieuNhapBUS;
import BUS.SachBUS;
import DTO.CTPhieuNhapHangDTO;
import DTO.CTPhieuNhapHangDTO;
import DTO.DocGiaDTO;
import DTO.NhaCungCapDTO;
import DTO.PhieuMuonDTO;
import DTO.PhieuNhapHangDTO;
import DTO.SachDTO;
import Util.Auth;
import Util.FormatDate;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author noname
 */
public class AddPhieuNhap extends javax.swing.JPanel {

    /**
     * Creates new form AddPhieuMuon
     */
    private String MaPN;
    private boolean isEdit;
    private MainPage mainPage;
    DefaultTableModel modelCt;
    ArrayList<CTPhieuNhapHangDTO> dsCTPN = new ArrayList<>();
    private PhieuNhapBUS bus = new PhieuNhapBUS();
    public static String currentMaPM;
    public AddPhieuNhap(MainPage main) {
        this.mainPage = main;
        initComponents();  
        modelCt = (DefaultTableModel) CTPNTable.getModel();
        xoaDong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private String generateMaPm(){
        PhieuNhapBUS bus = new PhieuNhapBUS();
        return bus.generateMaPN();
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNgayNhap = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtMaPn = new javax.swing.JTextField();
        txtNhanVien = new javax.swing.JTextField();
        txtNhaCungCap = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        CTPNTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnSave = new javax.swing.JButton();
        txtMaSach = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        btnDocGiaList = new javax.swing.JButton();
        btnSachList = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();

        setName("Chi tiết phiếu mượn"); // NOI18N
        setPreferredSize(new java.awt.Dimension(833, 861));

        jLabel1.setText("Mã PN");

        jLabel2.setText("Nhà cung cấp");

        jLabel3.setText("Ngày nhập");

        txtNgayNhap.setDateFormatString("yyyy-MM-dd");

        jLabel4.setText("Nhân viên");

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-return-30.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout btnBackLayout = new javax.swing.GroupLayout(btnBack);
        btnBack.setLayout(btnBackLayout);
        btnBackLayout.setHorizontalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnBackLayout.setVerticalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtMaPn.setText("jTextField1");

        txtNhanVien.setText("jTextField2");

        txtNhaCungCap.setText("jTextField3");

        CTPNTable.setModel(CTPNTable.getModel());
        jScrollPane2.setViewportView(CTPNTable);
        if (CTPNTable.getColumnModel().getColumnCount() > 0) {
            CTPNTable.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            CTPNTable.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            CTPNTable.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            CTPNTable.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        jLabel7.setText("Số lượng");

        jLabel8.setText("Mã sách");

        jButton1.setText("Thêm sách");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("jButton2");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnXoa.setText("[Xóa]");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThanhToan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnDocGiaList.setText("...");
        btnDocGiaList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocGiaListActionPerformed(evt);
            }
        });

        btnSachList.setText("...");
        btnSachList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSachListActionPerformed(evt);
            }
        });

        jLabel9.setText("Đơn giá");

        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSachList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaPn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDocGiaList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnSave)
                        .addGap(77, 77, 77)
                        .addComponent(btnThanhToan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtMaPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDocGiaList))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSachList)
                        .addComponent(jLabel9)
                        .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnXoa)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    //Hàm tạo form edit 
    public void initEditMode(String maPN){
        this.MaPN = maPN;
        isEdit = true;
        txtMaPn.setEditable(false);
        txtNhaCungCap.setEditable(false);
        btnDocGiaList.setEnabled(true);
        txtNhanVien.setEditable(false);
        btnXoa.setEnabled(false);
        txtMaSach.setText(null);
        txtDonGia.setText("");
        txtSoLuong.setText(null);
        btnSave.setText("Cập nhật");
//        PhieuNhapBUS phieuNhapBus = new PhieuNhapBUS();
//        PhieuNhapHangDTO pm = phieuNhapBus.getPNByMa(maPN);


//        System.out.println("MaPM nhận được: " + maP);

        loadPMByMaPm(maPN);
        loadData(maPN);
    }
    
        
    private void resetform(){
        PhieuNhapHangDTO dto = new PhieuNhapHangDTO();
        
        txtMaPn.setText("");
        txtNhaCungCap.setText(null);      
        txtMaSach.setText("");
        txtDonGia.setText("");
        txtSoLuong.setText(null);
        txtNhanVien.setText("");
        txtNgayNhap.setDate(null);
        
        dsCTPN.clear();
        modelCt.setRowCount(0);
    }
    //Hàm tạo form add 
    public void initAddMode() {
        isEdit = false;
        loadTableCt();
//        if (modelCt == null) dsCTPM = new ArrayList();
        resetform();
//        txtNhaCungCap.setEditable(true);
        txtMaPn.setText(bus.generateMaPN());
        txtMaPn.setEnabled(false);
        txtNgayNhap.setDate(new Date());
        btnXoa.setEnabled(true);
//        setMaSach(txtMaSach.getText());
        
        txtNhanVien.setEditable(false);
        txtNhanVien.setText(Auth.user.getMaNV());
        btnSave.setText("Thêm phiếu");
        revalidate();
        repaint();

}        
//    ===========Tạo hiển thị đơn giá khi chọn sách     
//    private void loadDonGia(){
//         String ma = txtMaSach.getText().trim();
//         if(ma.isEmpty()) return;
//         
//        SachBUS sachBus = new SachBUS();
//        SachDTO sachDto = sachBus.getSachByMa(ma);
//        if(sachDto != null){
//        txtDonGia.setText(String.valueOf(sachDto.getDonGia()));
//        }
//    }
//    public void setMaSach(String maSach){
//        txtMaSach.setText(maSach);
//        loadDonGia();
//    }
    
    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed
    
    private void xoaDong(){
        btnXoa.addActionListener(e -> {
        int row = CTPNTable.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn dòng cần xóa");
            return;
        }

        DefaultTableModel model =(DefaultTableModel) CTPNTable.getModel();
        dsCTPN.remove(row);
        model.removeRow(row);
});
    }
    
    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:      
        mainPage.showPNList();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        PhieuNhapHangDTO pn = new PhieuNhapHangDTO();       
        pn.setMaPNH(txtMaPn.getText());
        pn.setMaNCC(txtNhaCungCap.getText());
        pn.setMaNV(txtNhanVien.getText());
        pn.setNgayNhap(txtNgayNhap.getDate());
        
//        PhieuNhapBUS bus = new PhieuNhapBUS();
        validateForm();
        if(!isEdit){
        //Thêm
            boolean ok = bus.insert(pn, dsCTPN);
            if (ok){
                JOptionPane.showMessageDialog(this, "Thêm phiếu nhập thành công");
                resetform();               
            }
        }else{
        //Cập nhật===========
            boolean update = bus.updatePN(pn);
            if(update){
                JOptionPane.showMessageDialog(this, "Cập nhật phiếu mượn thành công");
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnXoaActionPerformed
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (dsCTPN == null){
             dsCTPN = new ArrayList();
        }

        SachBUS sachBus = new SachBUS();
        String ma = txtMaSach.getText();
        SachDTO sachDto = sachBus.getSachByMa(ma);
        int soluong = Integer.parseInt(txtSoLuong.getText());
        double donGia = Double.parseDouble(txtDonGia.getText());
        String tenSach = sachBus.getTenByMaSach(ma);
        boolean trungSach = false;
        
        for (int i = 0; i < CTPNTable.getRowCount(); i++){
            
            String maSachTable = modelCt.getValueAt(i, 0).toString();
            
            if(maSachTable.equals(ma)){
                int slCu = Integer.parseInt(modelCt.getValueAt(i, 2).toString());
                int slMoi = slCu + soluong;
                modelCt.setValueAt(slMoi, i, 2);
            
                //============================//4
                for (CTPhieuNhapHangDTO ct : dsCTPN){
                    if(ct.getMaSach().equals(ma)){
                        ct.setSl(slMoi);
                    }
                   }
                trungSach = true;
                }
            }
        if (!trungSach){
         CTPhieuNhapHangDTO ctpn  = new CTPhieuNhapHangDTO();
         double thanhTien = soluong * donGia;
         ctpn.setMaPn(txtMaPn.getText());
         ctpn.setMaSach(ma);
         ctpn.setSl(soluong);
         ctpn.setDonGia(donGia);
         ctpn.setThanhTien(thanhTien);
         dsCTPN.add(ctpn);   
         modelCt.addRow(new Object[]{
            ma,
            tenSach,
            soluong,
            donGia,
            thanhTien
        });
        }     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
//        PhieuMuonBUS pmBus = new PhieuMuonBUS();
//        pmBus.returnSach(MaPN);
//        JOptionPane.showMessageDialog(this, "Trả sách thành công");
//        mainPage.showPMList();
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnDocGiaListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocGiaListActionPerformed
        Frame parent = (Frame) SwingUtilities.getWindowAncestor(this);
        NhaCungCapDialog NhaCungCap = new NhaCungCapDialog(parent, true);
        NhaCungCap.setLocationRelativeTo(this);
        NhaCungCap.setVisible(true);
        
        NhaCungCapDTO dg = NhaCungCap.getSelectedNhaCungCap();
        if (dg != null){
            txtNhaCungCap.setText(dg.getMaNCC());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDocGiaListActionPerformed

    private void btnSachListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSachListActionPerformed
        // TODO add your handling code here:
        Frame parent = (Frame) SwingUtilities.getWindowAncestor(this);
        
        SachDialog.selectedSach = null;
        
        SachDialog sachDia = new SachDialog(parent, true);
        sachDia.setLocationRelativeTo(this);
        sachDia.setVisible(true);
        
        SachDTO sach = SachDialog.selectedSach;
        if(sach != null) txtMaSach.setText(sach.getMaSach());
    }//GEN-LAST:event_btnSachListActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed
     private void loadPMByMaPm(String MaPN){
        PhieuNhapBUS pn = new PhieuNhapBUS();
        PhieuNhapHangDTO dto = pn.getPNByMa(MaPN);
        
//        CTPhieuMuonBUS bus = new CTPhieuMuonBUS();       
//        bus.getCTPMByMaPm(MaPM);
                
        txtMaPn.setText(dto.getMaPNH());
        txtNhaCungCap.setText(dto.getMaNCC());
        txtNhanVien.setText(dto.getMaNV());
        txtNgayNhap.setDate(dto.getNgayNhap());

       
    }
    private void loadTableCt(){
//        CTPhieuMuonBUS bus = new CTPhieuMuonBUS();       
//        bus.getCTPMByMaPm(MaPM);
        Vector header = new Vector();
        header.add("Mã Sách");
        header.add("Tên Sách");
        header.add("Số lượng");
        header.add("Đơn giá");
        header.add("Thành tiền");
        
        modelCt= new DefaultTableModel(header, 0);
        
        CTPNTable.setModel(modelCt);
    }
    private void loadData(String MaPN){
        loadTableCt();
        CTPhieuNhapBUS busCt = new CTPhieuNhapBUS();
        dsCTPN = busCt.getCTPNByMaPm(MaPN);
        for(CTPhieuNhapHangDTO ctpn : dsCTPN){
            SachBUS sachBus = new SachBUS();
            String tenSach = sachBus.getTenByMaSach(ctpn.getMaSach());
            System.out.print(tenSach);
            Vector row = new Vector();
            row.add(ctpn.getMaSach());
            row.add(tenSach);
            row.add(ctpn.getSl());
            row.add(ctpn.getDonGia());
            row.add(ctpn.getThanhTien());
            modelCt.addRow(row);
            
    }
        CTPNTable.setModel(modelCt);
  }
    
     private void validateForm(){
        if (txtMaPn.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Chưa nhập mã phiếu nhập");
        return;
    }
        
        if (txtNhaCungCap.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Chưa chọn nhà cung cấp");
        return;
    }

    if (txtNgayNhap.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Chưa chọn ngày mượn");
        return;
    }


    if (dsCTPN.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Chưa có sách nào");
        return;
    }
  }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CTPNTable;
    private javax.swing.JPanel btnBack;
    private javax.swing.JButton btnDocGiaList;
    private javax.swing.JButton btnSachList;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaPn;
    private javax.swing.JTextField txtMaSach;
    private com.toedter.calendar.JDateChooser txtNgayNhap;
    private javax.swing.JTextField txtNhaCungCap;
    private javax.swing.JTextField txtNhanVien;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
