/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.CTPhieuMuonBUS;
import BUS.PhieuMuonBUS;
import BUS.PhieuPhatBUS;
import BUS.QuyDinhPhatBUS;
import BUS.SachBUS;
import DAO.SachDAO;
import DTO.CTPhieuMuonDTO;
import DTO.CTPhieuPhatDTO;
import DTO.PhieuMuonDTO;
import DTO.PhieuPhatDTO;
import DTO.QuyDinhPhatDTO;
import DTO.SachDTO;
import Util.Auth;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author noname
 */
public class AddPhieuPhat extends javax.swing.JPanel {

    /**
     * Creates new form AddPhieuPhat
     */
    private boolean isEdit = false;
    private String MaPP;
    private MainPage mainPage;
    DefaultTableModel modelCt;
    private CTPhieuMuonBUS pmBus;
    private ArrayList<QuyDinhPhatDTO> qdpDto = new ArrayList<>();
    ArrayList<CTPhieuPhatDTO> dsCTPP = new ArrayList<>();
    ArrayList<CTPhieuMuonDTO> dsCTPM = new ArrayList<>();
    
    public AddPhieuPhat(MainPage main) {
        this.mainPage = main;
//        modelCt = (DefaultTableModel) CTPPTable.getModel();
        initComponents();
        loadComboPhat();
        xoaDong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNgayMuon = new com.toedter.calendar.JDateChooser();
        txtHanTra = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtMaPP = new javax.swing.JTextField();
        txtNhanVien = new javax.swing.JTextField();
        txtDocGia = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        CTPPTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnThemSach = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnSave = new javax.swing.JButton();
        txtNgaytrathucte = new com.toedter.calendar.JDateChooser();
        traSach = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnSachList = new javax.swing.JButton();
        txtMaPm1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSoNgayTre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbxLyDo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtNgayLap = new com.toedter.calendar.JDateChooser();
        btnSave1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1250, 821));

        jPanel1.setName("Chi tiết phiếu mượn"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(833, 861));

        jLabel1.setText("Mã PP");

        jLabel2.setText("Độc giả ");

        jLabel3.setText("Ngày mượn");

        txtNgayMuon.setDateFormatString("yyyy-MM-dd");

        txtHanTra.setDateFormatString("yyyy-MM-dd");

        jLabel4.setText("Nhân viên");

        jLabel5.setText("Ngày trả");

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-return-30.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout btnBackLayout = new javax.swing.GroupLayout(btnBack);
        btnBack.setLayout(btnBackLayout);
        btnBackLayout.setHorizontalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnBackLayout.setVerticalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtMaPP.setText("jTextField1");
        txtMaPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPPActionPerformed(evt);
            }
        });

        txtNhanVien.setText("jTextField2");

        txtDocGia.setText("jTextField3");

        jScrollPane2.setViewportView(CTPPTable);

        jLabel7.setText("Số lượng");

        jLabel8.setText("Mã sách");

        btnThemSach.setText("Thêm sách");
        btnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSachActionPerformed(evt);
            }
        });

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("Thêm phiếu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtNgaytrathucte.setDateFormatString("yyyy-MM-dd\n");

        traSach.setText("Ngày trả thực tế");

        btnXoa.setText("[Xóa]");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSachList.setText("...");
        btnSachList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSachListActionPerformed(evt);
            }
        });

        txtMaPm1.setText("jTextField1");
        txtMaPm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPm1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Mã PM");

        jLabel11.setText("Tổng Tiền");

        txtTongTien.setText("jTextField1");

        jLabel6.setText("Số Ngày Trễ");

        txtSoNgayTre.setText("jTextField2");
        txtSoNgayTre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoNgayTreActionPerformed(evt);
            }
        });

        jLabel12.setText("Lý do");

        cbxLyDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLyDoActionPerformed(evt);
            }
        });

        jLabel13.setText("Ngày lập");

        txtNgayLap.setDateFormatString("yyyy-MM-dd");

        btnSave1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave1.setText("Thanh Toán");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaPP, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(traSach)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaPm1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgaytrathucte, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoNgayTre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(176, 176, 176)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHanTra, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(29, 29, 29)
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(66, 66, 66)
                                .addComponent(btnSave1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSachList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(cbxLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemSach)))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtMaPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtMaPm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(traSach)
                            .addComponent(txtNgaytrathucte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(txtSoNgayTre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHanTra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(46, 46, 46)
                        .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(btnThemSach)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSachList)
                    .addComponent(jLabel12)
                    .addComponent(cbxLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnXoa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadComboPhat(){
        DefaultComboBoxModel modelLoaiP = new DefaultComboBoxModel();
        QuyDinhPhatBUS bus = new QuyDinhPhatBUS();
        qdpDto = bus.getAll();
        for( QuyDinhPhatDTO dto : qdpDto){
//            cbxLyDo.addItem(dto.getMaQDP() +"-"+dto.getQuyDinh());
                modelLoaiP.addElement(dto);
        }
        cbxLyDo.setModel(modelLoaiP);
    }
    private String generateMaPP(){
        PhieuPhatBUS bus= new PhieuPhatBUS();
        return bus.generateMaPP();
    }
    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        mainPage.showPPList();
    }//GEN-LAST:event_btnBackMouseClicked

    public void initEditMode(String maPP){
        this.MaPP = maPP;
        isEdit = true;
        txtMaPP.setEditable(false);
        txtMaPm1.setEditable(false);
//        btnDocGiaList.setEnabled(true);
        txtNhanVien.setEditable(false);
        btnXoa.setEnabled(false);
        txtMaSach.setText(null);

        txtSoLuong.setText(null);
        btnSave.setVisible(false);
//        btnSave.setEnabled(true
//        PhieuPhatBUS phieuPhat = new PhieuPhatBUS();
//        PhieuPhatDTO pp = phieuPhat.getPPByMa(maPP);


//        System.out.println("MaPM nhận được: " + maP);

        loadPPByMaPp(maPP);
        loadData(maPP);
    }
    
    private void resetform(){
        PhieuMuonDTO dto = new PhieuMuonDTO();
        
//        txtDocGia.setText("");
////        txtNhanVien.setText("");
//        txtNgayMuon.setDate(null);
//        txtHanTra.setDate(null);       
//        cbTrangThai.setSelectedIndex(0);
//        
        txtMaSach.setText("");
        txtSoLuong.setText("");  
        txtTongTien.setText("0");

//        txtNgaytrathucte.setDate(null);
        if(dsCTPP != null) dsCTPP.clear();
        modelCt.setRowCount(0);
    }
    
    public void initAddMode(String maPm){
        isEdit = false;
        loadTableCt();
        if (modelCt == null) dsCTPP = new ArrayList();
        resetform();
        
//        PhieuPhatBUS ppBus = new PhieuPhatBUS();
        PhieuMuonBUS pmBus = new PhieuMuonBUS();
        PhieuMuonDTO pmDto = pmBus.getByMaPM(maPm);
        
        txtMaPP.setText(generateMaPP());
        txtMaPP.setEnabled(false);
        txtMaPm1.setText(pmDto.getMaPM());
        txtMaPm1.setEnabled(false);
        
        txtDocGia.setText(pmDto.getMaDG());
        txtDocGia.setEnabled(false);
        txtNhanVien.setText(pmDto.getMaNV());
        txtNhanVien.setEditable(false);
        
        txtNgayMuon.setDate(pmDto.getNgayMuon());
        txtHanTra.setDate(pmDto.getHanTra());
        txtNgayLap.setDate(new Date());
        txtNgaytrathucte.setDate(pmDto.getNgayTraThucTe());
        btnXoa.setEnabled(true);
        btnSave.setVisible(true);
        
        Date hanTra = pmDto.getHanTra();
        Date ngayTra =  pmDto.getNgayTraThucTe();
        PhieuPhatBUS bus = new PhieuPhatBUS();
        int soNgayTre = bus.tinhSoNgayTre(hanTra, ngayTra);
        txtSoNgayTre.setText(String.valueOf(soNgayTre));
        
        tinhTongTien();
        txtTongTien.revalidate();
        txtTongTien.repaint();
    }
    
    private void loadTableCt(){
//        CTPhieuMuonBUS bus = new CTPhieuMuonBUS();       
//        bus.getCTPMByMaPm(MaPM);
        Vector header = new Vector();
        header.add("Mã Sách");
        header.add("Tên Sách");
        header.add("Số lượng");
        header.add("Mã QDP");
        header.add("Ly do");
        header.add("Thanh tien");
        
        modelCt= new DefaultTableModel(header, 0);
        
        CTPPTable.setModel(modelCt);
    }
    
    private void loadPPByMaPp(String MaPP){
        PhieuPhatBUS pm = new PhieuPhatBUS();
        PhieuPhatDTO dto = pm.getPPByMa(MaPP);
        
        if(dto == null){
            JOptionPane.showMessageDialog(this, "Không tìm thấy phiếu phạt");
            return;
        }  
        String soNgayTre = String.valueOf(dto.getSoNgayTre());
        String tongTien =  String.valueOf(dto.getTongTien());
     
        txtMaPP.setText(dto.getMaPP());
        txtDocGia.setText(dto.getMaDG());
        txtNhanVien.setText(dto.getMaNV());
        txtNgayLap.setDate(dto.getNgayLap());
        txtMaPm1.setText(dto.getMaPM());
        txtSoNgayTre.setText(soNgayTre);
        txtTongTien.setText(tongTien);
         
        PhieuMuonBUS pmBus = new PhieuMuonBUS();
        PhieuMuonDTO pmDto = pmBus.getByMaPM(txtMaPm1.getText());
        
        txtNgayMuon.setDate(pmDto.getNgayMuon());
        txtHanTra.setDate(pmDto.getHanTra());
       

       
    }
    private void loadData(String MaPP){
        loadTableCt();
//        modelCt.setRowCount(0);
        PhieuPhatBUS bus = new PhieuPhatBUS();
        dsCTPP = bus.getCTByMaPP(MaPP);
        for(CTPhieuPhatDTO ctpp : dsCTPP){
            SachBUS sachBus = new SachBUS();
            String tenSach = sachBus.getTenByMaSach(ctpp.getMaSach());
            System.out.print(tenSach);
            Vector row = new Vector();
            row.add(ctpp.getMaSach());
            row.add(tenSach);
            row.add(ctpp.getSoLuong());
            row.add(ctpp.getQdPhat());
            row.add(ctpp.getLyDo());
            row.add(ctpp.getThanhTien());
            modelCt.addRow(row);
            
    }
//        CTPPTable.setModel(modelCt);

  }
    private void tinhTongTien(){
        int soNgayTre = Integer.parseInt(txtSoNgayTre.getText());
        PhieuPhatBUS bus = new PhieuPhatBUS();
        double tong = bus.tinhTongTien(dsCTPP, soNgayTre);
        txtTongTien.setText(String.valueOf(tong));
        System.out.println("Tổng Tiền:"  +tong);
        txtTongTien.revalidate();
        txtTongTien.repaint();
        
    }
    
    
    private void btnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSachActionPerformed
        if (dsCTPP == null){
            dsCTPP = new ArrayList();
        }
            SachBUS sachBus = new SachBUS();
            String ma = txtMaSach.getText();
            int soluong = Integer.parseInt(txtSoLuong.getText());
            String tenSach = sachBus.getTenByMaSach(ma);
            
            
            int slCon = 0;
            for (CTPhieuMuonDTO ct : dsCTPM){
                if(ct.getMaSach().equals(ma)) slCon += ct.getSoLuong();
            }
            
            for (CTPhieuPhatDTO ct : dsCTPP){
                if(ct.getMaSach().equals(ma)) slCon -= ct.getSoLuong();
            }
            
            if (soluong > slCon){
                JOptionPane.showMessageDialog(this, "Số lượng không đủ");
            } else {
            //===================================//
            QuyDinhPhatDTO selected =  (QuyDinhPhatDTO) cbxLyDo.getSelectedItem();
            if (selected == null) return;
            String maQdp = selected.getMaQDP();
//            int soTienPhat = selected.getSoTienPhat();
            PhieuPhatBUS ppBus = new PhieuPhatBUS();
//            int soNgayTre = Integer.parseInt(txtSoNgayTre.getText());
            double thanhtien = ppBus.tinhTien(maQdp, soluong);
            
            
//            System.out.println(maQdp + "-" + soTienPhat + "-"+ thanhtien);
            
            boolean trungSach = false;
            for (int i = 0; i < CTPPTable.getRowCount(); i++){
                String maSachTable = modelCt.getValueAt(i, 0).toString();
                String maQdpTable = modelCt.getValueAt(i, 3).toString();
                if(maSachTable.equals(ma) && selected.getMaQDP().equals(maQdpTable)){
                    int slCu = Integer.parseInt(modelCt.getValueAt(i, 2).toString());
                    int slMoi = slCu + soluong;
                    double thanhTienMoi = ppBus.tinhTien(maQdp, slMoi);
                    
                    modelCt.setValueAt(slMoi, i, 2);
                    modelCt.setValueAt(thanhTienMoi, i, 5);
                    //============================//4
                    for (CTPhieuPhatDTO ct : dsCTPP){
                        if(ct.getMaSach().equals(ma)){
                            ct.setSoLuong(slMoi);
                            ct.setThanhTien(thanhTienMoi);
                        }
                    }
                    trungSach = true;
                }
            }
            if (!trungSach){
                CTPhieuPhatDTO ctpp  = new CTPhieuPhatDTO();
                ctpp.setMaPP(txtMaPP.getText());
                ctpp.setMaSach(ma);
                ctpp.setQdPhat(maQdp);
                ctpp.setSoLuong(soluong);
                ctpp.setThanhTien(thanhtien);
                ctpp.setLyDo(selected.getQuyDinh());
                dsCTPP.add(ctpp);
                modelCt.addRow(new Object[]{
                    ma,
                    tenSach,
                    soluong,
                    maQdp,
                    selected.getQuyDinh(),
                    thanhtien
                });
            }
            modelCt.fireTableDataChanged();
            tinhTongTien();    
            txtTongTien.revalidate();
            txtTongTien.repaint();
        }
       
    }//GEN-LAST:event_btnThemSachActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        PhieuPhatDTO pp = new PhieuPhatDTO();
        pp.setMaPP(txtMaPP.getText());
        pp.setMaPM(txtMaPm1.getText());
        pp.setMaDG(txtDocGia.getText());
        pp.setMaNV(txtNhanVien.getText());
        pp.setNgayLap(txtNgayLap.getDate());
        int soNgaytre = Integer.parseInt(txtSoNgayTre.getText());
        pp.setSoNgayTre(soNgaytre);
        pp.setTongTien(Double.parseDouble(txtTongTien.getText()));
        pp.setTrangThai(cbxLyDo.getSelectedIndex()); // 0,1,2
        
        PhieuPhatBUS bus = new PhieuPhatBUS();
        
        if(bus.daCoPhieuPhat(txtMaPm1.getText())){
               JOptionPane.showMessageDialog(this, "Phiếu mượn đã có phiếu phạt");
                    return;
            }
        //Thêm
        if(!isEdit){
            boolean ok = bus.insertPP(pp, dsCTPP);
            if (ok){
                for(CTPhieuPhatDTO ct : dsCTPP){
                    for(int i = 0; i < dsCTPP.size(); i++){
                    String lyDo = modelCt.getValueAt(i, 4).toString();
                    dsCTPP.get(i).setLyDo(lyDo);
                }
            }
                JOptionPane.showMessageDialog(this, "Thêm phiếu phạt thành công");
    //            resetform();
            }
            else JOptionPane.showMessageDialog(this, "Thêm phiếu phạt không thành công");
        }
        //Sửa===========
        else if(isEdit){
            boolean ok = bus.updatePP(pp, dsCTPP);
            if (ok){
                JOptionPane.showMessageDialog(this, "Sửa phiếu phạt thành công");
    //            resetform();
            }
            else JOptionPane.showMessageDialog(this, "Sửa phiếu phạt không thành công");
        }
        
       

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed
        private void xoaDong(){
        btnXoa.addActionListener(e -> {
        int row = CTPPTable.getSelectedRow();       
        
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn dòng cần xóa");
            return;
        }
        if(row >= 0) {
            String maSachTable = modelCt.getValueAt(row, 0).toString();
            String maQdpTable = modelCt.getValueAt(row, 3).toString();
        DefaultTableModel model =(DefaultTableModel) CTPPTable.getModel();
        dsCTPP.removeIf(ct -> ct.getMaSach().equals(maSachTable) && ct.getQdPhat().equals(maQdpTable));
        model.removeRow(row);
        tinhTongTien();
        }
    });
    }
    
    private void btnSachListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSachListActionPerformed
        // TODO add your handling code here:
        pmBus = new CTPhieuMuonBUS();
        dsCTPM = pmBus.getCTPMByMaPm(AddPhieuMuon.currentMaPM);     
        Frame parent = (Frame) SwingUtilities.getWindowAncestor(this);
        SachMuonDialog sachDia = new SachMuonDialog(parent, true, dsCTPM, dsCTPP);
        sachDia.setLocationRelativeTo(this);
        sachDia.setVisible(true);

        CTPhieuMuonDTO ctpm = sachDia.getSelectedSach();
        if(ctpm != null) txtMaSach.setText(ctpm.getMaSach());
        
//        loadData(AddPhieuMuon.currentMaPM);
//        tinhTongTien();
    }//GEN-LAST:event_btnSachListActionPerformed

    private void txtMaPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPPActionPerformed

    private void txtMaPm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPm1ActionPerformed

    private void txtSoNgayTreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoNgayTreActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoNgayTreActionPerformed

    private void cbxLyDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLyDoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxLyDoActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSave1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CTPPTable;
    private javax.swing.JPanel btnBack;
    private javax.swing.JButton btnSachList;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnThemSach;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxLyDo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel traSach;
    private javax.swing.JTextField txtDocGia;
    private com.toedter.calendar.JDateChooser txtHanTra;
    private javax.swing.JTextField txtMaPP;
    private javax.swing.JTextField txtMaPm1;
    private javax.swing.JTextField txtMaSach;
    private com.toedter.calendar.JDateChooser txtNgayLap;
    private com.toedter.calendar.JDateChooser txtNgayMuon;
    private com.toedter.calendar.JDateChooser txtNgaytrathucte;
    private javax.swing.JTextField txtNhanVien;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoNgayTre;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
