/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.CTPhieuMuonBUS;
import BUS.PhieuMuonBUS;
import BUS.PhieuNhapBUS;
import BUS.SachBUS;
import DTO.CTPhieuMuonDTO;
import DTO.DocGiaDTO;
import DTO.PhieuMuonDTO;
import DTO.SachDTO;
import Util.Auth;
import Util.FormatDate;
import java.awt.Frame;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author noname
 */
public class AddPhieuMuon extends javax.swing.JPanel {

    /**
     * Creates new form AddPhieuMuon
     */
    private String MaPM;
    private boolean isEdit;
    private MainPage mainPage;
    DefaultTableModel modelCt;
    ArrayList<CTPhieuMuonDTO> dsCTPM = new ArrayList<>();
    public static String currentMaPM;
    public AddPhieuMuon(MainPage main) {
        this.mainPage = main;
        initComponents();  
        loadTrangThai();
        modelCt = (DefaultTableModel) CTPMTable.getModel();
        xoaDong();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private String generateMaPm(){
        PhieuMuonBUS bus = new PhieuMuonBUS();
        return bus.generateMaPM();
    }
    
    private void loadTrangThai(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("Đang mượn");
        model.addElement("Đã Trả");
        model.addElement("Quá Hạn");
        cbTrangThai.setModel(model);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNgayMuon = new com.toedter.calendar.JDateChooser();
        txtHanTra = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtMaPm = new javax.swing.JTextField();
        txtNhanVien = new javax.swing.JTextField();
        txtDocGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbTrangThai = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        CTPMTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnSave = new javax.swing.JButton();
        txtNgaytrathucte = new com.toedter.calendar.JDateChooser();
        traSach = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnTraSach = new javax.swing.JButton();
        btnPhieuphat = new javax.swing.JButton();
        btnDocGiaList = new javax.swing.JButton();
        btnSachList = new javax.swing.JButton();

        setName("Chi tiết phiếu mượn"); // NOI18N
        setPreferredSize(new java.awt.Dimension(833, 861));

        jLabel1.setText("Mã PM");

        jLabel2.setText("Độc giả ");

        jLabel3.setText("Ngày mượn");

        txtNgayMuon.setDateFormatString("yyyy-MM-dd");

        txtHanTra.setDateFormatString("yyyy-MM-dd");

        jLabel4.setText("Nhân viên");

        jLabel5.setText("Ngày trả");

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-return-30.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout btnBackLayout = new javax.swing.GroupLayout(btnBack);
        btnBack.setLayout(btnBackLayout);
        btnBackLayout.setHorizontalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnBackLayout.setVerticalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtMaPm.setText("jTextField1");

        txtNhanVien.setText("jTextField2");

        txtDocGia.setText("jTextField3");

        jLabel6.setText("Trạng thái");

        cbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CTPMTable.setModel(CTPMTable.getModel());
        jScrollPane2.setViewportView(CTPMTable);
        if (CTPMTable.getColumnModel().getColumnCount() > 0) {
            CTPMTable.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            CTPMTable.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            CTPMTable.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            CTPMTable.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        jLabel7.setText("Số lượng");

        jLabel8.setText("Mã sách");

        btnThem.setText("Thêm sách");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("jButton2");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtNgaytrathucte.setDateFormatString("yyyy-MM-dd");

        traSach.setText("Ngày trả thực tế");

        btnXoa.setText("[Xóa]");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTraSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTraSach.setText("jButton2");
        btnTraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraSachActionPerformed(evt);
            }
        });

        btnPhieuphat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPhieuphat.setText("jButton2");
        btnPhieuphat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuphatActionPerformed(evt);
            }
        });

        btnDocGiaList.setText("...");
        btnDocGiaList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocGiaListActionPerformed(evt);
            }
        });

        btnSachList.setText("...");
        btnSachList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSachListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSachList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnThem)
                        .addGap(132, 132, 132)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 791, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaPm, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDocGiaList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHanTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(19, 19, 19)
                        .addComponent(traSach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgaytrathucte, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnSave)
                        .addGap(77, 77, 77)
                        .addComponent(btnTraSach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPhieuphat)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHanTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtMaPm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btnDocGiaList))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(cbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(traSach))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNgaytrathucte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(btnThem)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSachList))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTraSach, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPhieuphat, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnXoa)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    //Hàm tạo form edit 
    public void initEditMode(String maPM){
        this.MaPM = maPM;
        isEdit = true;
        traSach.setVisible(true);
        txtNgaytrathucte.setVisible(true);
        txtMaPm.setEditable(false);
        txtDocGia.setEditable(false);
        btnDocGiaList.setEnabled(true);
        txtNhanVien.setEditable(false);
//        txtNgayMuon.setEditable(false);
//        txtHanTra.setEditable(false);
        btnSave.setText("Cập nhật");
        btnSave.setEnabled(true);
        PhieuMuonBUS phieuMuonBus = new PhieuMuonBUS();
        PhieuMuonDTO pm = phieuMuonBus.getByMaPM(maPM);

        LocalDate today = LocalDate.now();

        LocalDate hanTra = ((java.sql.Date) pm.getHanTra()).toLocalDate();

        txtNgaytrathucte.setDate(new Date());

        btnPhieuphat.setText("Tạo phiếu phạt");
        btnTraSach.setText("Trả Sách");

        // reset mặc định
        btnTraSach.setVisible(false);
        btnPhieuphat.setVisible(false);

        if(pm.getTrangThai() == 1){ 
            // Đã trả
            btnSave.setEnabled(false);
            btnDocGiaList.setEnabled(false);
            cbTrangThai.setEnabled(false);
        }

        else if(pm.getTrangThai() == 2){
            // Đã tạo phiếu phạt
            btnSave.setEnabled(true);
            btnSave.setText("Xác nhận ngày trả");
            cbTrangThai.setEnabled(false);
            btnPhieuphat.setVisible(true);
        }

        else{

           if (today.isAfter(hanTra)) {
                // Thực sự quá hạn
                btnTraSach.setVisible(false);
                btnPhieuphat.setVisible(true);
            } else {
                // Còn hạn hoặc đúng ngày hạn
                btnTraSach.setVisible(true);
                btnPhieuphat.setVisible(false);
            }
        }

        System.out.println("MaPM nhận được: " + maPM);

        loadPMByMaPm(maPM);
        loadData(maPM);
    }
    
        
    private void resetform(){
        PhieuMuonDTO dto = new PhieuMuonDTO();
        
        txtDocGia.setText("");
//        txtNhanVien.setText("");
        txtNgayMuon.setDate(null);
        txtHanTra.setDate(null);       
        cbTrangThai.setSelectedIndex(0);
        
        txtMaSach.setText("");
        txtSoLuong.setText("");       
        txtNgaytrathucte.setDate(null);
        
        dsCTPM.clear();
        modelCt.setRowCount(0);
    }
    //Hàm tạo form add 
    public void initAddMode() {
        isEdit = false;
        loadTableCt();
        if (dsCTPM == null) dsCTPM = new ArrayList();
        resetform();
        txtDocGia.setEditable(true);
        traSach.setVisible(false);
        txtNgayMuon.setDate(new Date());
        txtNgaytrathucte.setVisible(false);
        txtMaPm.setText(generateMaPm());
        txtMaPm.setEnabled(false);
        txtNhanVien.setEditable(false);
        txtNhanVien.setText(Auth.user.getMaNV());
        btnSave.setText("Thêm phiếu");
        btnTraSach.setVisible(false);
        btnPhieuphat.setVisible(false);
        btnXoa.setEnabled(true);
//        CTPhieuMuonBUS.dsCTPM.clear();
        revalidate();
        repaint();

}        
    
    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed
    
    private void xoaDong(){
        btnXoa.addActionListener(e -> {
        int row = CTPMTable.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn dòng cần xóa");
            return;
        }

        DefaultTableModel model =(DefaultTableModel) CTPMTable.getModel();
        dsCTPM.remove(row);
        model.removeRow(row);
});
    }
    
    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:      
        mainPage.showPMList();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        PhieuMuonDTO pm = new PhieuMuonDTO();       
        pm.setMaPM(txtMaPm.getText());
        pm.setMaDG(txtDocGia.getText());
        pm.setMaNV(txtNhanVien.getText());
        pm.setNgayMuon(txtNgayMuon.getDate());
        pm.setHanTra(txtHanTra.getDate());
        
        Date today = new Date();
        Date hanTra = pm.getHanTra();
        
        PhieuMuonBUS bus = new PhieuMuonBUS();
        validateForm();
        if(!isEdit){
        //Thêm
            boolean ok = bus.insert(pm, dsCTPM);
            if (ok){
                JOptionPane.showMessageDialog(this, "Thêm phiếu mượn thành công");
                resetform();                
            }
                }else if(today.after(hanTra)){
                //Cập nhật===========//
                    boolean update = bus.updateNgayTra(pm.getMaPM());
                    if(update){
                        JOptionPane.showMessageDialog(this, "Xác nhận ngày trả thành công");
                    }
            }else {
                boolean update = bus.updatePM(pm, dsCTPM);
                if(update){
                    JOptionPane.showMessageDialog(this, "Cập nhật phiếu mượn thành công");
                }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    }//GEN-LAST:event_btnXoaActionPerformed
    
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (dsCTPM == null){
             dsCTPM = new ArrayList();
        }
      
        
//        for (int i = 0; i <= modelCt.getRowCount(); i++){
//        CTPhieuMuonDTO ctpm  = new CTPhieuMuonDTO();
        SachBUS sachBus = new SachBUS();
        String ma = txtMaSach.getText();
        int soluong = 0;
        try {
            soluong = Integer.parseInt(txtSoLuong.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ");
            return;
        }
        String tenSach = sachBus.getTenByMaSach(ma);
        boolean trungSach = false;
        
        for (int i = 0; i < CTPMTable.getRowCount(); i++){
            
            String maSachTable = modelCt.getValueAt(i, 0).toString();
            
            if(maSachTable.equals(ma)){
                int slCu = Integer.parseInt(modelCt.getValueAt(i, 2).toString());
                int slMoi = slCu + soluong;
                modelCt.setValueAt(slMoi, i, 2);
            
                //============================//4
                for (CTPhieuMuonDTO ct : dsCTPM){
                    if(ct.getMaSach().equals(ma)){
                        ct.setSoLuong(slMoi);
                    }
                   }
                trungSach = true;
                }
            }
        if (!trungSach){
         CTPhieuMuonDTO ctpm  = new CTPhieuMuonDTO();
         ctpm.setMaPM(txtMaPm.getText());
         ctpm.setMaSach(ma);
         ctpm.setSoLuong(soluong);
         dsCTPM.add(ctpm);   
         modelCt.addRow(new Object[]{
            ma,
            tenSach,
            soluong,
        });
        }     
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraSachActionPerformed
        // TODO add your handling code here:
        PhieuMuonBUS pmBus = new PhieuMuonBUS();
        pmBus.returnSach(MaPM);
        JOptionPane.showMessageDialog(this, "Trả sách thành công");
        mainPage.showPMList();
    }//GEN-LAST:event_btnTraSachActionPerformed

    private void btnPhieuphatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuphatActionPerformed
        // TODO add your handling code here:
        currentMaPM = txtMaPm.getText();
        PhieuMuonBUS pmBus = new PhieuMuonBUS();
        if(pmBus.getByMaPM(MaPM).getNgayTraThucTe() == null){
            JOptionPane.showMessageDialog(this, "Hãy xác nhận ngày trả sách");
        } else {
        mainPage.showAddPhieuPhat(currentMaPM);
        }
    }//GEN-LAST:event_btnPhieuphatActionPerformed

    private void btnDocGiaListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocGiaListActionPerformed
        Frame parent = (Frame) SwingUtilities.getWindowAncestor(this);
        DocGiaDialog docGia = new DocGiaDialog(parent, true);
        docGia.setLocationRelativeTo(this);
        docGia.setVisible(true);
        
        DocGiaDTO dg = docGia.getSelectedDocGia();
        if (dg != null){
            txtDocGia.setText(dg.getMaDG());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDocGiaListActionPerformed

    private void btnSachListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSachListActionPerformed
        // TODO add your handling code here:
        Frame parent = (Frame) SwingUtilities.getWindowAncestor(this);
        
        SachDialog.selectedSach = null;
        
        SachDialog sachDia = new SachDialog(parent, true);
        sachDia.setLocationRelativeTo(this);
        sachDia.setVisible(true);
        
        SachDTO sach = SachDialog.selectedSach;
        
//        SachDTO sach = sachDia.getSelectedSach();
        if(sach != null) txtMaSach.setText(sach.getMaSach());
    }//GEN-LAST:event_btnSachListActionPerformed
     private void loadPMByMaPm(String MaPM){
        PhieuMuonBUS pm = new PhieuMuonBUS();
        PhieuMuonDTO dto = pm.getByMaPM(MaPM);
        
//        CTPhieuMuonBUS bus = new CTPhieuMuonBUS();       
//        bus.getCTPMByMaPm(MaPM);
        
        int trangthai = dto.getTrangThai();
        
        txtMaPm.setText(dto.getMaPM());
        txtDocGia.setText(dto.getMaDG());
        txtNhanVien.setText(dto.getMaNV());
        txtNgayMuon.setDate(dto.getNgayMuon());
        txtHanTra.setDate(dto.getHanTra());
        cbTrangThai.setSelectedIndex(trangthai);
        if(trangthai == 0) txtNgaytrathucte.setDate(new Date());
        else txtNgaytrathucte.setDate(dto.getNgayTraThucTe());
       
    }
    private void loadTableCt(){
//        CTPhieuMuonBUS bus = new CTPhieuMuonBUS();       
//        bus.getCTPMByMaPm(MaPM);
        Vector header = new Vector();
        header.add("Mã Sách");
        header.add("Tên Sách");
        header.add("Số lượng");     
        
        modelCt= new DefaultTableModel(header, 0);
        
        CTPMTable.setModel(modelCt);
    }
    private void loadData(String MaPM){
        loadTableCt();
        CTPhieuMuonBUS busCt = new CTPhieuMuonBUS();
        dsCTPM = busCt.getCTPMByMaPm(MaPM);
        for(CTPhieuMuonDTO ctpm : dsCTPM){
            SachBUS sachBus = new SachBUS();
            String tenSach = sachBus.getTenByMaSach(ctpm.getMaSach());
            System.out.print(tenSach);
            Vector row = new Vector();
            row.add(ctpm.getMaSach());
            row.add(tenSach);
            row.add(ctpm.getSoLuong());
            modelCt.addRow(row);
            
    }
        CTPMTable.setModel(modelCt);
  }
    private void validateForm(){
        if (txtDocGia.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Chưa chọn độc giả");
        return;
    }

    if (txtNgayMuon.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Chưa chọn ngày mượn");
        return;
    }

    if (txtHanTra.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Chưa chọn hạn trả");
        return;
    }

    if (dsCTPM.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Chưa có sách nào");
        return;
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CTPMTable;
    private javax.swing.JPanel btnBack;
    private javax.swing.JButton btnDocGiaList;
    private javax.swing.JButton btnPhieuphat;
    private javax.swing.JButton btnSachList;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTraSach;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel traSach;
    private javax.swing.JTextField txtDocGia;
    private com.toedter.calendar.JDateChooser txtHanTra;
    private javax.swing.JTextField txtMaPm;
    private javax.swing.JTextField txtMaSach;
    private com.toedter.calendar.JDateChooser txtNgayMuon;
    private com.toedter.calendar.JDateChooser txtNgaytrathucte;
    private javax.swing.JTextField txtNhanVien;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
