/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import BUS.PhieuMuonBUS;
import java.awt.CardLayout;
import java.awt.Color;
import javax.smartcardio.Card;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author noname
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    CardLayout cardlayout;
    sachForm sach = new sachForm();
    docgiaForm docgia = new docgiaForm();
    nhanvienForm nhanvien = new nhanvienForm();
    phieuPhatForm phieuphat = new phieuPhatForm();
    phieuMuonForm phieumuon = new phieuMuonForm(this);
    AddPhieuMuon addPM = new AddPhieuMuon(this);
    
    public MainPage() {
        initComponents();
        addMenuEffect(pnSach);
        addMenuEffect(pnDocGia);
        addMenuEffect(pnNhanVien);
        addMenuEffect(pnMuonTra);
        addMenuEffect(pnPhieuPhat);
        addMenuEffect(pnNhapSach);
        addMenuEffect(pnThongKe);

    // Mặc định chọn Sách
        
        cardlayout = (CardLayout) content.getLayout();
        currentMenu = pnSach;
        pnSach.setBackground(COLOR_ACTIVE);

        content.add(sach, "sach_list");
        content.add(docgia, "docgia_list");
        content.add(nhanvien, "nhanvien_list");
        content.add(phieuphat, "phieuphat_list");
        content.add(phieumuon,"phieumuon_list");
        content.add(addPM,"addPM" );
        sach.setVisible(false);
        docgia.setVisible(false);
        nhanvien.setVisible(false);
        phieuphat.setVisible(false);
        phieumuon.setVisible(false);
        
    }

    Color COLOR_DEFAULT = new Color(31,58,95);
    Color COLOR_HOVER   = new Color(31,33,95);
    Color COLOR_ACTIVE  = new Color(31,33,95); // đang chọn
    private JPanel currentMenu = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        pnSach = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnDocGia = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnNhanVien = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnMuonTra = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnPhieuPhat = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pnNhapSach = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        pnThongKe = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnClose = new javax.swing.JPanel();
        lblClose1 = new javax.swing.JLabel();
        content = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1450, 850));
        setSize(new java.awt.Dimension(1450, 850));

        pnMenu.setBackground(new java.awt.Color(31, 58, 95));
        pnMenu.setPreferredSize(new java.awt.Dimension(200, 800));

        pnSach.setBackground(new java.awt.Color(31, 58, 95));
        pnSach.setForeground(new java.awt.Color(255, 255, 255));
        pnSach.setPreferredSize(new java.awt.Dimension(136, 55));
        pnSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnSachMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-realbook-24.png"))); // NOI18N
        jLabel4.setText("Quản lý sách");

        javax.swing.GroupLayout pnSachLayout = new javax.swing.GroupLayout(pnSach);
        pnSach.setLayout(pnSachLayout);
        pnSachLayout.setHorizontalGroup(
            pnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSachLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnSachLayout.setVerticalGroup(
            pnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnDocGia.setBackground(new java.awt.Color(31, 58, 95));
        pnDocGia.setForeground(new java.awt.Color(255, 255, 255));
        pnDocGia.setPreferredSize(new java.awt.Dimension(136, 55));
        pnDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnDocGiaMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-book-24.png"))); // NOI18N
        jLabel7.setText("Quản lý độc giả ");

        javax.swing.GroupLayout pnDocGiaLayout = new javax.swing.GroupLayout(pnDocGia);
        pnDocGia.setLayout(pnDocGiaLayout);
        pnDocGiaLayout.setHorizontalGroup(
            pnDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDocGiaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDocGiaLayout.setVerticalGroup(
            pnDocGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDocGiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnNhanVien.setBackground(new java.awt.Color(31, 58, 95));
        pnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        pnNhanVien.setPreferredSize(new java.awt.Dimension(136, 55));
        pnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnNhanVienMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-staff-24.png"))); // NOI18N
        jLabel8.setText("Quản lý nhân viên");

        javax.swing.GroupLayout pnNhanVienLayout = new javax.swing.GroupLayout(pnNhanVien);
        pnNhanVien.setLayout(pnNhanVienLayout);
        pnNhanVienLayout.setHorizontalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhanVienLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnNhanVienLayout.setVerticalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnMuonTra.setBackground(new java.awt.Color(31, 58, 95));
        pnMuonTra.setForeground(new java.awt.Color(255, 255, 255));
        pnMuonTra.setPreferredSize(new java.awt.Dimension(136, 55));
        pnMuonTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMuonTraMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-check-book-24.png"))); // NOI18N
        jLabel9.setText("Mượn - Trả Sách");

        javax.swing.GroupLayout pnMuonTraLayout = new javax.swing.GroupLayout(pnMuonTra);
        pnMuonTra.setLayout(pnMuonTraLayout);
        pnMuonTraLayout.setHorizontalGroup(
            pnMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMuonTraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMuonTraLayout.setVerticalGroup(
            pnMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMuonTraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnPhieuPhat.setBackground(new java.awt.Color(31, 58, 95));
        pnPhieuPhat.setForeground(new java.awt.Color(255, 255, 255));
        pnPhieuPhat.setPreferredSize(new java.awt.Dimension(136, 55));
        pnPhieuPhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnPhieuPhatMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-refund-24.png"))); // NOI18N
        jLabel15.setText("Phiếu phạt");

        javax.swing.GroupLayout pnPhieuPhatLayout = new javax.swing.GroupLayout(pnPhieuPhat);
        pnPhieuPhat.setLayout(pnPhieuPhatLayout);
        pnPhieuPhatLayout.setHorizontalGroup(
            pnPhieuPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhieuPhatLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnPhieuPhatLayout.setVerticalGroup(
            pnPhieuPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhieuPhatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnNhapSach.setBackground(new java.awt.Color(31, 58, 95));
        pnNhapSach.setForeground(new java.awt.Color(255, 255, 255));
        pnNhapSach.setPreferredSize(new java.awt.Dimension(136, 55));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-import-24.png"))); // NOI18N
        jLabel16.setText("Nhập sách ");

        javax.swing.GroupLayout pnNhapSachLayout = new javax.swing.GroupLayout(pnNhapSach);
        pnNhapSach.setLayout(pnNhapSachLayout);
        pnNhapSachLayout.setHorizontalGroup(
            pnNhapSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhapSachLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnNhapSachLayout.setVerticalGroup(
            pnNhapSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhapSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnThongKe.setBackground(new java.awt.Color(31, 58, 95));
        pnThongKe.setForeground(new java.awt.Color(255, 255, 255));
        pnThongKe.setPreferredSize(new java.awt.Dimension(136, 55));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-statistics-24.png"))); // NOI18N
        jLabel17.setText("Thống kê");

        javax.swing.GroupLayout pnThongKeLayout = new javax.swing.GroupLayout(pnThongKe);
        pnThongKe.setLayout(pnThongKeLayout);
        pnThongKeLayout.setHorizontalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongKeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThongKeLayout.setVerticalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-logout-32.png"))); // NOI18N
        jLabel10.setText("Đăng xuất ");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-library-64.png"))); // NOI18N

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(pnSach, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(pnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(pnMuonTra, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(pnPhieuPhat, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(pnNhapSach, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(pnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnMenuLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10))
                            .addGroup(pnMenuLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addGap(108, 108, 108)
                .addComponent(pnSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnMuonTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnPhieuPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnNhapSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(19, 19, 19))
        );

        getContentPane().add(pnMenu, java.awt.BorderLayout.LINE_START);

        pnHeader.setBackground(new java.awt.Color(46, 92, 138));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Library Management System");

        pnClose.setBackground(new java.awt.Color(46, 92, 138));
        pnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnCloseMouseExited(evt);
            }
        });

        lblClose1.setBackground(new java.awt.Color(255, 255, 255));
        lblClose1.setForeground(new java.awt.Color(255, 255, 255));
        lblClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        lblClose1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClose1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnCloseLayout = new javax.swing.GroupLayout(pnClose);
        pnClose.setLayout(pnCloseLayout);
        pnCloseLayout.setHorizontalGroup(
            pnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCloseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClose1)
                .addContainerGap())
        );
        pnCloseLayout.setVerticalGroup(
            pnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClose1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 767, Short.MAX_VALUE)
                .addComponent(pnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnHeader, java.awt.BorderLayout.PAGE_START);

        content.setLayout(new java.awt.CardLayout());
        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void pnSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnSachMouseClicked
        // TODO add your handling code here:
//        sach.setVisible(true);
//        docgia.setVisible(false);
//        nhanvien.setVisible(false);
//        phieuphat.setVisible(false);
//        phieumuon.setVisible(false);
          cardlayout.show(content, "sach_list");
    }//GEN-LAST:event_pnSachMouseClicked
   //=====================Phieu muon=======================
    public void showPMList() {
//        PhieuMuonBUS pmBus  = new PhieuMuonBUS();
//        pmBus.getAll();
        cardlayout.show(content, "phieumuon_list");
}
    public void showAddPhieuMuon() {
        addPM.initAddMode();        // reset form
        cardlayout.show(content, "addPM");
}
    public void showEditPhieuMuon(String maPM) {
        addPM.initEditMode(maPM);        // reset form
        cardlayout.show(content, "addPM");
}
   //================================================================//
    
    private void pnDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDocGiaMouseClicked
        // TODO add your handling code here:
//        sach.setVisible(false);
//        docgia.setVisible(true);
//        nhanvien.setVisible(false);
//        phieuphat.setVisible(false);
//        phieumuon.setVisible(false);
          cardlayout.show(content, "docgia_list");
    }//GEN-LAST:event_pnDocGiaMouseClicked

    private void pnNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNhanVienMouseClicked
        // TODO add your handling code here:
//        sach.setVisible(false);
//        docgia.setVisible(false);
//        nhanvien.setVisible(true);
//        phieuphat.setVisible(false);
//        phieumuon.setVisible(false);
          cardlayout.show(content, "nhanvien_list");
    }//GEN-LAST:event_pnNhanVienMouseClicked

    private void lblClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblClose1MouseClicked

    private void lblClose1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseEntered
        // TODO add your handling code here:
        pnClose.setBackground(Color.RED);
    }//GEN-LAST:event_lblClose1MouseEntered

    private void pnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pnCloseMouseClicked

    private void pnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnCloseMouseEntered
        // TODO add your handling code here:
        pnClose.setBackground(Color.RED);
    }//GEN-LAST:event_pnCloseMouseEntered

    private void pnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnCloseMouseExited
        // TODO add your handling code here:
        pnClose.setBackground(new Color(46,92,138));
    }//GEN-LAST:event_pnCloseMouseExited

    private void pnPhieuPhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPhieuPhatMouseClicked
        // TODO add your handling code here:
//        sach.setVisible(false);
//        docgia.setVisible(false);
//        nhanvien.setVisible(false);
//        phieuphat.setVisible(true);
//        phieumuon.setVisible(false);
          cardlayout.show(content, "phieuphat_list");
    }//GEN-LAST:event_pnPhieuPhatMouseClicked

    private void pnMuonTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMuonTraMouseClicked
        // TODO add your handling code here:
//        sach.setVisible(false);
//        docgia.setVisible(false);
//        nhanvien.setVisible(false);
//        phieuphat.setVisible(false);
//        phieumuon.setVisible(true);
          cardlayout.show(content, "phieumuon_list");
    }//GEN-LAST:event_pnMuonTraMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        LoginForm login = new LoginForm();
        JOptionPane.showMessageDialog(this, "Xác nhận đăng xuất ?");
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked
 
    private void addMenuEffect(JPanel menuPanel) {

    menuPanel.addMouseListener(new java.awt.event.MouseAdapter() {

        @Override
        public void mouseEntered(java.awt.event.MouseEvent e) {
            if (menuPanel != currentMenu) {
                menuPanel.setBackground(COLOR_HOVER);
            }
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent e) {
            if (menuPanel != currentMenu) {
                menuPanel.setBackground(COLOR_DEFAULT);
            }
        }

        @Override
        public void mouseClicked(java.awt.event.MouseEvent e) {
            if (currentMenu != null) {
                currentMenu.setBackground(COLOR_DEFAULT);
            }
            currentMenu = menuPanel;
            currentMenu.setBackground(COLOR_ACTIVE);
        }
    });
}   
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblClose1;
    private javax.swing.JPanel pnClose;
    private javax.swing.JPanel pnDocGia;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnMuonTra;
    private javax.swing.JPanel pnNhanVien;
    private javax.swing.JPanel pnNhapSach;
    private javax.swing.JPanel pnPhieuPhat;
    private javax.swing.JPanel pnSach;
    private javax.swing.JPanel pnThongKe;
    // End of variables declaration//GEN-END:variables
}
