/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.PhieuPhatBUS;
import DTO.PhieuPhatDTO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author noname
 */
public class phieuPhatForm extends javax.swing.JPanel {

    /**
     * Creates new form phieuPhatForm
     */
    private MainPage mainPage;
    private PhieuPhatBUS phieuPhatBus = new PhieuPhatBUS();
    private ArrayList<PhieuPhatDTO> listPp  = new ArrayList<>();
    private ArrayList<PhieuPhatDTO> currentList;

    public phieuPhatForm(MainPage main) {
        this.mainPage = main;
        initComponents();
        loadList();
        initEdit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTimkiem4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhieuPhat = new javax.swing.JTable();

        pnTimkiem4.setBackground(new java.awt.Color(255, 255, 255));
        pnTimkiem4.setPreferredSize(new java.awt.Dimension(1237, 60));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Tìm kiếm theo tên ");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-interface-symbol.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        btnEdit.setText("Chi tiết");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (1).png"))); // NOI18N
        btnLamMoi.setText("Lam moi");
        btnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseClicked(evt);
            }
        });
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTimkiem4Layout = new javax.swing.GroupLayout(pnTimkiem4);
        pnTimkiem4.setLayout(pnTimkiem4Layout);
        pnTimkiem4Layout.setHorizontalGroup(
            pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimkiem4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEdit)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addGap(179, 179, 179)
                .addComponent(btnLamMoi)
                .addGap(19, 19, 19))
        );
        pnTimkiem4Layout.setVerticalGroup(
            pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimkiem4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimkiem4Layout.createSequentialGroup()
                        .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimkiem4Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTimkiem4Layout.createSequentialGroup()
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimkiem4Layout.createSequentialGroup()
                                .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21))))))
        );

        tblPhieuPhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPhieuPhat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTimkiem4, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTimkiem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here: tìm kiếm
        phieuPhatBus = new PhieuPhatBUS();
        String keyword = txtSearch.getText();
        if(keyword.isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã phiếu phạt");
            return;
        }
        
        ArrayList<PhieuPhatDTO> searchList = phieuPhatBus.searchByMaPP(keyword, currentList);
        if(searchList == null){
            JOptionPane.showMessageDialog(null, "Không tìm thấy phiếu phạt");
        }else{
            loadData(searchList);
//            ArrayList<PhieuMuonDTO> result = new ArrayList<>();
//            result.add(dto);   
//            loadData(result);
//            System.out.println(dto.getMaPM());
//            System.out.print(result);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
//        AddBookForm bookForm = new AddBookForm();
//        bookForm.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed
    
    public void loadList(){
        phieuPhatBus = new PhieuPhatBUS();
        listPp = phieuPhatBus.getAll();
        currentList = new ArrayList<>(listPp);
        loadData(currentList);
    }
    
     public void loadData(ArrayList<PhieuPhatDTO> pnList){
        PhieuPhatBUS PhieuPhatBus = new PhieuPhatBUS();
        PhieuPhatDTO pm = new PhieuPhatDTO();
        
        if(listPp == null ) phieuPhatBus.getAll();
        Vector header = new Vector();
        header.add("Mã Phiếu Phạt");
        header.add("Mã Phiếu Mượn");
        header.add("Mã độc giả");
        header.add("Ngày Lập");
        header.add("Tổng Tiền");
        header.add("Trạng thái");
        
        DefaultTableModel modelPp= new DefaultTableModel(header,0);
        modelPp.setRowCount(0);
        
        for(PhieuPhatDTO pp : pnList){
            Vector row = new Vector();
            row.add(pp.getMaPP());
            row.add(pp.getMaPM());
            row.add(pp.getMaDG());
            row.add(pp.getNgayLap());
            row.add(pp.getTongTien());
            row.add(pp.getTrangThaiString());

            modelPp.addRow(row);
                      
        }
            tblPhieuPhat.setModel(modelPp);
        
    }
    
     
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPhieuPhat.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phiếu phạt cần xóa!");
            return;
        }
        // Lấy mã phiếu phạt từ bảng
        String maPP = tblPhieuPhat.getValueAt(selectedRow, 0).toString();

        // Xác nhận trước khi xóa
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Bạn có chắc muốn xóa phiếu phạt " + maPP + " ?", 
            "Xác nhận", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            PhieuPhatBUS bus = new PhieuPhatBUS();
            boolean ok = bus.deletePP(maPP);

            if (ok) {
                JOptionPane.showMessageDialog(this, "Xóa phiếu phạt thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa phiếu phạt thất bại");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnLamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoiMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        PhieuPhatBUS pmBus = new PhieuPhatBUS();
        currentList = pmBus.getAll();
        loadData(currentList);
    }//GEN-LAST:event_btnLamMoiActionPerformed
    private void initEdit(){
        btnEdit.addActionListener(e -> {
            int row = tblPhieuPhat.getSelectedRow();
            System.out.println("Row: " + row);
            
            if (row >= 0) {
            for (int i = 0; i < tblPhieuPhat.getColumnCount(); i++) {
                System.out.println("Col " + i + ": " + tblPhieuPhat.getValueAt(row, i));
            }
            }
            if(row == -1){
                JOptionPane.showMessageDialog(this, "Vui long chon 1 phieu phat");
                return;
            }
            String maPP = tblPhieuPhat.getValueAt(row, 0).toString();
            System.out.println("Mã pp: " + maPP);
            if(maPP != null) mainPage.showEditPhieuPhat(maPP);   
            else{
                 JOptionPane.showMessageDialog(this, "Không tìm thấy phiếu phạt");
        }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnTimkiem4;
    private javax.swing.JTable tblPhieuPhat;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
