/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Content.CT_PhieuMuon;
import BUS.PhieuMuonBUS;
import DTO.PhieuMuonDTO;
import DTO.SachDTO;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author noname
 */
public class phieuMuonForm extends javax.swing.JPanel {

    /**
     * Creates new form phieuMuonForm
     */
    private MainPage mainPage;
    private PhieuMuonBUS phieuMuonBus;
    private ArrayList<PhieuMuonDTO> listPm  = new ArrayList<>();
    private ArrayList<PhieuMuonDTO> currentList;
    public phieuMuonForm(MainPage main) {
        initComponents();
        this.mainPage = main;
        loaiNgay();
        loadList();
        initAdd();
        initEdit();
        phieuMuonTable.setDefaultEditor(Object.class, null);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        pnTimkiem4 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        cbxLoaiNgay = new javax.swing.JComboBox<>();
        txtTuNgay = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLoc = new javax.swing.JButton();
        txtDenNgay = new com.toedter.calendar.JDateChooser();
        cbxTrangThai = new javax.swing.JComboBox<>();
        btnExport = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        phieuMuonTable = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pnTimkiem4.setBackground(new java.awt.Color(255, 255, 255));
        pnTimkiem4.setPreferredSize(new java.awt.Dimension(1237, 60));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-interface-symbol.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        btnSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSearchKeyPressed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (1).png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btnEdit.setText("Xem chi tiet");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (1).png"))); // NOI18N
        btnAdd1.setText("Lam moi");
        btnAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd1MouseClicked(evt);
            }
        });
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        cbxLoaiNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtTuNgay.setDateFormatString("yyyy-MM-dd");

        jLabel1.setText("Từ Ngày");

        jLabel2.setText("Đến Ngày");

        jLabel3.setText("Tìm kiếm");

        jLabel4.setText("Bộ lọc");

        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        txtDenNgay.setDateFormatString("yyyy-MM-dd");

        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-export-32.png"))); // NOI18N
        btnExport.setText("Xuất Excel");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTimkiem4Layout = new javax.swing.GroupLayout(pnTimkiem4);
        pnTimkiem4.setLayout(pnTimkiem4Layout);
        pnTimkiem4Layout.setHorizontalGroup(
            pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimkiem4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnTimkiem4Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit))
                    .addGroup(pnTimkiem4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbxLoaiNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTimkiem4Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnTimkiem4Layout.createSequentialGroup()
                        .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(cbxTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnExport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd1)
                        .addGap(39, 39, 39))))
        );
        pnTimkiem4Layout.setVerticalGroup(
            pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimkiem4Layout.createSequentialGroup()
                .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTimkiem4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbxLoaiNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1))
                            .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnTimkiem4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(btnLoc)
                                .addComponent(cbxTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(btnEdit))
                    .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch)
                            .addComponent(jLabel3))
                        .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        phieuMuonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(phieuMuonTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTimkiem4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTimkiem4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        phieuMuonBus = new PhieuMuonBUS();
        String keyWord = txtSearch.getText();
        ArrayList<PhieuMuonDTO> searchList = phieuMuonBus.searchByMaPm(keyWord, currentList);
        if(searchList == null){
            JOptionPane.showMessageDialog(null, "Không tìm thấy phiếu mượn");
        }else{
//            ArrayList<PhieuMuonDTO> result = new ArrayList<>();
//            result.add(dto);   
//            loadData(result);
              loadData(searchList);
//            System.out.println(dto.getMaPM());
//            System.out.print(result);
        }
        // TODO add your handling code h
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
//        AddBookForm bookForm = new AddBookForm();
//        bookForm.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed
   //=======Hàm gọi content mainpage cho add và edit 
    private void initAdd(){
        btnAdd.addActionListener(e -> {
           mainPage.showAddPhieuMuon();
        });
    }
    private void initEdit(){
        btnEdit.addActionListener(e -> {
        int row = phieuMuonTable.getSelectedRow();
                    if(row == -1 ){
                       JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 phiếu mượn");
                            return;
                        }
                    String maPm = phieuMuonTable.getValueAt(row, 0).toString();
//                    btnEdit.addActionListener(e -> {
                    mainPage.showEditPhieuMuon(maPm);
                     });
 }
    //====================================================================//
    
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnAdd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd1MouseClicked

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        PhieuMuonBUS pmBus = new PhieuMuonBUS();
        currentList = pmBus.getAll();
        pmBus.updateQuaHan();
        loadData(currentList);
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        // TODO add your handling code here:
        filter();
    }//GEN-LAST:event_btnLocActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSearchKeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnSearchKeyPressed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          if (!txtSearch.getText().isEmpty()) {
                btnSearch.doClick();  
            }
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("D:\\Netbeans Projects\\QuanLyThuVien\\src\\Export");
        //        fileChooser.setDialogTitle("Chọn nơi lưu file");
        //        String userHome = System.getProperty("user.home");
        //        File desktop = new File(userHome + "\\QuanLyThuVien\\src\\Export\\PhieuPhat_Export");

        //        fileChooser.setSelectedFile(desktop);
        int userSelection = fileChooser.showSaveDialog(this);

        if(userSelection == JFileChooser.APPROVE_OPTION){
            //            File defaultFile = new File("D:\\Netbeans Projects\\QuanLyThuVien\\src\\Export\\PhieuPhat_Export");
            File fileToSave = fileChooser.getSelectedFile();

            String path = fileToSave.getAbsolutePath() + ".xlsx";

            PhieuMuonBUS bus = new PhieuMuonBUS();
            ArrayList<PhieuMuonDTO> list = bus.getAll();

            bus.exportPhieuMuonToExcel(list, path);
        }
    }//GEN-LAST:event_btnExportActionPerformed
    private void filter(){
        phieuMuonBus = new PhieuMuonBUS();
        String loaiNgay = cbxLoaiNgay.getSelectedItem().toString();
        Date tuNgay = txtTuNgay.getDate();
        Date denNgay = txtDenNgay.getDate();
        if (tuNgay != null && denNgay != null && tuNgay.getTime()>denNgay.getTime())
        {
            JOptionPane.showMessageDialog(null, "Nhập sai ngày");
            txtTuNgay.requestFocus();
            return;
        }
        
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        int trangThai = cbxTrangThai.getSelectedIndex() - 1;
        
        currentList = phieuMuonBus.filter(loaiNgay, trangThai, tuNgay, denNgay);
        loadData(currentList);
    }
    private void loadList(){
        phieuMuonBus = new PhieuMuonBUS();
        listPm = phieuMuonBus.getAll();
        currentList = new ArrayList<>(listPm);
        phieuMuonBus.updateQuaHan();
        loadData(currentList);
    }
    private void loaiNgay(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("Tất cả");
        model.addElement("Ngày Mượn");
        model.addElement("Hạn Trả");
        model.addElement("Ngày Trả Thực Tế");
        
        cbxLoaiNgay.setModel(model);
    
        DefaultComboBoxModel model1 = new DefaultComboBoxModel();
        model1.addElement("Tất cả");
        model1.addElement("Đang mượn");
        model1.addElement("Đã Trả");
        model1.addElement("Quá Hạn");
        
        cbxTrangThai.setModel(model1);
    }
  
//Hàm đổ dữ liệu cho table chi tiết
    private void loadData(ArrayList<PhieuMuonDTO> list){
        PhieuMuonBUS phieuMuonBus = new PhieuMuonBUS();
        PhieuMuonDTO pm = new PhieuMuonDTO();
        
        if(phieuMuonBus.dsPhieuMuon == null ) phieuMuonBus.getAll();
        Vector header = new Vector();
        header.add("Mã Phiếu Mượn");
        header.add("Mã Độc Giả");
        header.add("Mã Nhân Viên");
        header.add("Ngày Mượn");
        header.add("Ngày Trả");
        header.add("Ngày trả thực tế");
        header.add("Trạng thái");
        
        DefaultTableModel modelPm = new DefaultTableModel(header,0);
        modelPm.setRowCount(0);
        
        for(PhieuMuonDTO phieumuon : list){
            Vector now = new Vector();
            now.add(phieumuon.getMaPM());
            now.add(phieumuon.getMaDG());
            now.add(phieumuon.getMaNV());
            now.add(phieumuon.getNgayMuon());
            now.add(phieumuon.getHanTra());
            now.add(phieumuon.getNgayTraThucTe());
            now.add(phieumuon.getTrangThaiString());
            modelPm.addRow(now);
                      
        }
            phieuMuonTable.setModel(modelPm);
        
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbxLoaiNgay;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable phieuMuonTable;
    private javax.swing.JPanel pnTimkiem4;
    private com.toedter.calendar.JDateChooser txtDenNgay;
    private javax.swing.JTextField txtSearch;
    private com.toedter.calendar.JDateChooser txtTuNgay;
    // End of variables declaration//GEN-END:variables
}
