/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.SachBUS;
import static BUS.SachBUS.dsSach;
import DAO.SachDAO;
import DTO.SachDTO;
import DTO.TheLoaiDTO;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author noname
 */
public class sachForm extends javax.swing.JPanel {

    /**
     * Creates new form sachForm
     */
    public sachForm() {
        initComponents();
        loadData();
        loadThongKeTheLoaiCombo();
    }
    
    //tạo combobox thong ke
    private void loadThongKeTheLoaiCombo() {
        cbxTheLoai.removeAllItems(); // clear trước
        SachBUS bus = new SachBUS();
        Set<String> setTheLoai = new HashSet<>(); // Set giúp tự động lọc trùng

    for (SachDTO item : SachBUS.dsSach) {
        String tenTL = bus.getTenByMaTL(item.getMaTL());
        if (tenTL != null) {
            setTheLoai.add(tenTL); 
        }
    }
    cbxTheLoai.addItem("Không");
    for (String theLoai : setTheLoai) {
        cbxTheLoai.addItem(theLoai);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnTimkiem4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        addBook3 = new javax.swing.JButton();
        editBook3 = new javax.swing.JButton();
        deleteBook3 = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        cbxTheLoai = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        sachTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1201, 830));

        pnTimkiem4.setBackground(new java.awt.Color(255, 255, 255));
        pnTimkiem4.setPreferredSize(new java.awt.Dimension(1237, 60));

        jLabel16.setText("Tìm kiếm");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-interface-symbol.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        addBook3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (1).png"))); // NOI18N
        addBook3.setText("Thêm");
        addBook3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBook3MouseClicked(evt);
            }
        });
        addBook3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBook3ActionPerformed(evt);
            }
        });

        editBook3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        editBook3.setText("Sửa");
        editBook3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBook3ActionPerformed(evt);
            }
        });

        deleteBook3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        deleteBook3.setText("Xóa");
        deleteBook3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBook3ActionPerformed(evt);
            }
        });

        btnAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (1).png"))); // NOI18N
        btnAdd1.setText("Làm mới");
        btnAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd1MouseClicked(evt);
            }
        });
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-export-32.png"))); // NOI18N
        btnExport.setText("Xuất Excel");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        cbxTheLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thống kê tổng hợp" }));
        cbxTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTheLoaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTimkiem4Layout = new javax.swing.GroupLayout(pnTimkiem4);
        pnTimkiem4.setLayout(pnTimkiem4Layout);
        pnTimkiem4Layout.setHorizontalGroup(
            pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimkiem4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBook3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editBook3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBook3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addGap(26, 26, 26)
                .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnTimkiem4Layout.setVerticalGroup(
            pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimkiem4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editBook3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(addBook3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBook3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnTimkiem4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(cbxTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sachTable.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        sachTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(sachTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTimkiem4, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTimkiem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // tìm kiếm theo tên
    String keyword = jTextField5.getText().trim();
    
    // Kiểm tra an toàn cho ComboBox
    Object selectedItem = cbxTheLoai.getSelectedItem();
    String theloai = (selectedItem != null) ? selectedItem.toString() : "Không";

    SachBUS bus = new SachBUS();
    
    //Tìm kiếm danh sách sách theo tu khoa
    ArrayList<SachDTO> listSearch = bus.searchSach(keyword);
    
    // Tạo một danh sách mới để chứa kết quả cuối cùng
    ArrayList<SachDTO> resultList = new ArrayList<>();

    //Lọc theo thể loại
    if (theloai.equals("Không")) {
        // Nếu không chọn thể loại cụ thể, lấy toàn bộ kết quả tìm kiếm
        resultList = listSearch;
    } else {
        // Nếu có chọn thể loại, tiến hành lọc
        for (SachDTO sach : listSearch) {
            // SỬA LỖI: Dùng đúng hàm lấy Tên Thể Loại qua tầng BUS
            String tenTheLoaiCuaSach = bus.getTenByMaTL(sach.getMaTL());
            
            // So sánh tên thể loại của sách với tên thể loại đang chọn
            if (tenTheLoaiCuaSach != null && tenTheLoaiCuaSach.equals(theloai)) {
                resultList.add(sach);
            }
        }
    }

    //Đổ dữ liệu ra bảng
    DefaultTableModel model = (DefaultTableModel) sachTable.getModel();
    model.setRowCount(0); // Xóa trắng bảng cũ
    
     for(SachDTO sach : resultList){

            model.addRow(new Object[]{
                sach.getMaSach(),
                sach.getTenSach(),
                bus.getTenByMaTL(sach.getMaTL()),
                bus.getTenByMaTG(sach.getMaTG()),
                bus.getTenNXBByMaNXB(sach.getMaNXB()),
                sach.getNgayXB(),
                sach.getSoLuong(),
                sach.getDonGia()
            });
    }
        
    }                                        

    private void addBook3MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void addBook3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // nút thêm
        AddBookForm bookForm = new AddBookForm();
        bookForm.setVisible(true);
    }                                        

    private void editBook3ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // nút sửa
        int selectedRow = sachTable.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sách muốn sửa");
            return;
        }
        
        String maSach = (String)sachTable.getValueAt(selectedRow, 0);
        String tenSach = (String)sachTable.getValueAt(selectedRow, 1);
        String maTL = (String)sachTable.getValueAt(selectedRow, 2);
        String maTG = (String)sachTable.getValueAt(selectedRow, 3);
        String maNXB = (String)sachTable.getValueAt(selectedRow, 4);
        Date ngayXB = (Date)sachTable.getValueAt(selectedRow, 5);
        int soLuong = (int)sachTable.getValueAt(selectedRow, 6);
        double donGia = (double)sachTable.getValueAt(selectedRow, 7);
        
        SachDTO sach1 = new SachDTO(maSach, tenSach, maTL, maTG, maNXB, ngayXB, soLuong, donGia);
        
        AddBookForm bookForm = new AddBookForm();
        bookForm.setModeSua(sach1);
        bookForm.setVisible(true);
    }                                         

    private void deleteBook3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // Xóa
        int selectedRow = sachTable.getSelectedRow();
        String maSach = sachTable.getValueAt(selectedRow, 0).toString();
        
        SachBUS bus = new SachBUS();
        boolean ok = bus.deleteSach(maSach);
        
        if(ok){
            JOptionPane.showMessageDialog(null, "Xóa sách thành công");
        }
        else if(!ok){
            JOptionPane.showMessageDialog(null, "Xóa sách thất bại");
        }
    }                                           

    private void btnAdd1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        SachBUS sachBus = new SachBUS();
        sachBus.getALL();
        loadData();
    }                                       

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("D:\\Netbeans Projects\\QuanLyThuVien\\src\\Export");

        int userSelection = fileChooser.showSaveDialog(this);

        if(userSelection == JFileChooser.APPROVE_OPTION){
            //            File defaultFile = new File("D:\\Netbeans Projects\\QuanLyThuVien\\src\\Export\\PhieuPhat_Export");
            File fileToSave = fileChooser.getSelectedFile();

            String path = fileToSave.getAbsolutePath() + ".xlsx";

            SachBUS bus = new SachBUS();
            ArrayList<SachDTO> list = bus.getALL();

            bus.exportSachToExcel(list, path);
        }
    }                                         

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("D:\\Netbeans Projects\\QuanLyThuVien\\src\\ImportSample");
        fileChooser.setDialogTitle("Chọn file Excel");

        int result = fileChooser.showOpenDialog(this);

        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();

            SachBUS bus = new SachBUS();
            bus.importSachFromExcel(selectedFile);

            loadData(); // reload lại bảng
        }
    }                                         

    private void cbxTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          
    private void customizeTable() {
    sachTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // cho phép chỉnh tay

    sachTable.getColumnModel().getColumn(0).setPreferredWidth(80);   // Mã sách
    sachTable.getColumnModel().getColumn(1).setPreferredWidth(320);  // Tên sách
    sachTable.getColumnModel().getColumn(2).setPreferredWidth(170);  // Thể loại
    sachTable.getColumnModel().getColumn(3).setPreferredWidth(180);  // Tác giả
    sachTable.getColumnModel().getColumn(4).setPreferredWidth(140);  // NXB
    sachTable.getColumnModel().getColumn(5).setPreferredWidth(140);  // Năm XB
    sachTable.getColumnModel().getColumn(6).setPreferredWidth(80);   // Số lượng
    sachTable.getColumnModel().getColumn(7).setPreferredWidth(120);  // Đơn giá
    
    sachTable.setRowHeight(32);
    sachTable.setFont(new Font("Segoe UI", Font.PLAIN, 14));
  
    sachTable.getTableHeader().setFont(
        new Font("Segoe UI", Font.BOLD, 16)
    );
    sachTable.getTableHeader().setPreferredSize(
        new Dimension(sachTable.getWidth(), 40)
    );
}
    private void loadData(){
        SachBUS sachBus = new SachBUS();
        if(SachBUS.dsSach == null) sachBus.getALL();
        Vector header = new Vector();
        header.add("Mã Sách");
        header.add("Tên Sách");
        header.add("Thể loại");
        header.add("Tác giả");
        header.add("Nhà xuất bản");
        header.add("Năm xuất bản");
        header.add("Số lượng");
        header.add("Đơn giá");
        
        DefaultTableModel model = new DefaultTableModel(header,0);
        for(SachDTO sach: SachBUS.dsSach){
            Vector now = new Vector();
            now.add(sach.getMaSach());
            now.add(sach.getTenSach());
            now.add(sachBus.getTenByMaTL(sach.getMaTL()));
            now.add(sachBus.getTenByMaTG(sach.getMaTG()));
            now.add(sachBus.getTenNXBByMaNXB(sach.getMaNXB()));
            now.add(sach.getNgayXB());
            now.add(sach.getSoLuong());
            now.add(sach.getDonGia());
            model.addRow(now);
      
        }
        sachTable.setModel(model);
        customizeTable();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addBook3;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnImport;
    private javax.swing.JComboBox<String> cbxTheLoai;
    private javax.swing.JButton deleteBook3;
    private javax.swing.JButton editBook3;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel pnTimkiem4;
    private javax.swing.JTable sachTable;
    // End of variables declaration                   
}
