/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.SachBUS;
import DTO.SachDTO;
import java.awt.Dimension;
import java.awt.Font;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author noname
 */
public class sachForm extends javax.swing.JPanel {

    /**
     * Creates new form sachForm
     */
    public sachForm() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTimkiem4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        addBook3 = new javax.swing.JButton();
        editBook3 = new javax.swing.JButton();
        deleteBook3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sachTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1201, 830));

        pnTimkiem4.setBackground(new java.awt.Color(255, 255, 255));
        pnTimkiem4.setPreferredSize(new java.awt.Dimension(1237, 60));

        jLabel16.setText("Tìm kiếm theo tên ");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-interface-symbol.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        addBook3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (1).png"))); // NOI18N
        addBook3.setText("Thêm");
        addBook3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBook3MouseClicked(evt);
            }
        });
        addBook3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBook3ActionPerformed(evt);
            }
        });

        editBook3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        editBook3.setText("Sửa");
        editBook3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBook3ActionPerformed(evt);
            }
        });

        deleteBook3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        deleteBook3.setText("Xóa");
        deleteBook3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBook3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTimkiem4Layout = new javax.swing.GroupLayout(pnTimkiem4);
        pnTimkiem4.setLayout(pnTimkiem4Layout);
        pnTimkiem4Layout.setHorizontalGroup(
            pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimkiem4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBook3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBook3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBook3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addGap(159, 159, 159))
        );
        pnTimkiem4Layout.setVerticalGroup(
            pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimkiem4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(pnTimkiem4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimkiem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBook3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editBook3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBook3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sachTable.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        sachTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(sachTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTimkiem4, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTimkiem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void addBook3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBook3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addBook3MouseClicked

    private void addBook3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBook3ActionPerformed
        // TODO add your handling code here:
        AddBookForm bookForm = new AddBookForm();
        bookForm.setVisible(true);
    }//GEN-LAST:event_addBook3ActionPerformed

    private void editBook3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBook3ActionPerformed
        // TODO add your handling code here:
        AddBookForm bookForm = new AddBookForm();
        bookForm.setVisible(true);
    }//GEN-LAST:event_editBook3ActionPerformed

    private void deleteBook3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBook3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBook3ActionPerformed
    private void customizeTable() {
    sachTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // cho phép chỉnh tay

    sachTable.getColumnModel().getColumn(0).setPreferredWidth(80);   // Mã sách
    sachTable.getColumnModel().getColumn(1).setPreferredWidth(400);  // Tên sách
    sachTable.getColumnModel().getColumn(2).setPreferredWidth(220);  // Thể loại
    sachTable.getColumnModel().getColumn(3).setPreferredWidth(200);  // NXB
    sachTable.getColumnModel().getColumn(4).setPreferredWidth(140);  // Năm XB
    sachTable.getColumnModel().getColumn(5).setPreferredWidth(80);   // Số lượng
    sachTable.getColumnModel().getColumn(6).setPreferredWidth(150);     
    
    sachTable.setRowHeight(32);
    sachTable.setFont(new Font("Segoe UI", Font.PLAIN, 14));
  
    sachTable.getTableHeader().setFont(
        new Font("Segoe UI", Font.BOLD, 16)
    );
    sachTable.getTableHeader().setPreferredSize(
        new Dimension(sachTable.getWidth(), 40)
    );
}
    private void loadData(){
        SachBUS sachBus = new SachBUS();
        if(SachBUS.dsSach == null) sachBus.getALL();
        Vector header = new Vector();
        header.add("Mã Sách");
        header.add("Tên Sách");
        header.add("Thể loại");
        header.add("Nhà xuất bản");
        header.add("Năm xuất bản");
        header.add("Số lượng");
        header.add("Đơn giá");
        
        DefaultTableModel model = new DefaultTableModel(header,0);
        for(SachDTO sach: SachBUS.dsSach){
            Vector now = new Vector();
            now.add(sach.getMaSach());
            now.add(sach.getTenSach());
            now.add(sach.getMaTL());
            now.add(sach.getMaNXB());
            now.add(sach.getNgayXB());
            now.add(sach.getSoLuong());
            now.add(sach.getDonGia());
            model.addRow(now);
      
        }
        sachTable.setModel(model);
        customizeTable();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBook3;
    private javax.swing.JButton deleteBook3;
    private javax.swing.JButton editBook3;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel pnTimkiem4;
    private javax.swing.JTable sachTable;
    // End of variables declaration//GEN-END:variables
}
