/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.CTPhieuMuonBUS;
import BUS.DocGiaBUS;
import BUS.PhieuMuonBUS;
import BUS.PhieuPhatBUS;
import BUS.SachBUS;
import DTO.CTPhieuMuonDTO;
import DTO.DocGiaDTO;
import DTO.PhieuMuonDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author noname
 */
  

    public class ThongKeForm extends javax.swing.JPanel {

        /**
         * Creates new form ThongKeForm
         */
        private SachBUS sachBus = new SachBUS();
        private PhieuMuonBUS pmBus = new PhieuMuonBUS();
        private PhieuPhatBUS phatBus = new PhieuPhatBUS();

        Color PRIMARY = new Color(25, 118, 210);     // xanh chính
        Color PRIMARY_LIGHT = new Color(144, 202, 249);
        Color BACKGROUND = new Color(245, 247, 250);
        Color CARD_BG = Color.WHITE;
        Color TEXT_DARK = new Color(33, 33, 33);

        public ThongKeForm() {
            initComponents();
            setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));
            styleFilterPanel();
            styleTable();
            loadlistDocGiaSach(null,null);
//        loadBarChart();

            //==============làm đẹp background===============// 
            setBackground(BACKGROUND);
            pnlFilter.setBackground(CARD_BG);
            pnTop.setBackground(BACKGROUND);
            pnChart.setBackground(CARD_BG);
            tableDocGiaSach.setBackground(Color.WHITE);
            //==============làm đẹp background===============// 

//        initTopPanel();
            initChartPanel();
            loadThongKe();

        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlFilter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnThongKe = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtTuNgay = new com.toedter.calendar.JDateChooser();
        txtDenNgay = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDocGiaSach = new javax.swing.JTable();
        pnTop = new javax.swing.JPanel();
        pnChart = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1250, 821));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Thống Kê");

        jLabel2.setText("Từ Ngày:");

        jLabel3.setText("Đến Ngày:");

        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFilterLayout = new javax.swing.GroupLayout(pnlFilter);
        pnlFilter.setLayout(pnlFilterLayout);
        pnlFilterLayout.setHorizontalGroup(
            pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilterLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 620, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addGap(14, 14, 14))
        );
        pnlFilterLayout.setVerticalGroup(
            pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFilterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThongKe)
                        .addComponent(btnReset)))
                .addGap(10, 10, 10))
        );

        tableDocGiaSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableDocGiaSach);

        javax.swing.GroupLayout pnTopLayout = new javax.swing.GroupLayout(pnTop);
        pnTop.setLayout(pnTopLayout);
        pnTopLayout.setHorizontalGroup(
            pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnTopLayout.setVerticalGroup(
            pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnChartLayout = new javax.swing.GroupLayout(pnChart);
        pnChart.setLayout(pnChartLayout);
        pnChartLayout.setHorizontalGroup(
            pnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnChartLayout.setVerticalGroup(
            pnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jLabel4.setText("                                                                                                                                                                    Danh sách độc giả đã mượn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(1126, 1126, 1126)))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnChart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnTop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(pnlFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
//==============làm đẹp filter===============//

    private void styleFilterPanel() {
        pnlFilter.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createEmptyBorder(10, 15, 10, 15),
                BorderFactory.createLineBorder(new Color(220, 220, 220))
        ));

        btnThongKe.setBackground(PRIMARY);
        btnThongKe.setForeground(Color.WHITE);
        btnThongKe.setFocusPainted(false);

        btnReset.setBackground(Color.WHITE);
        btnReset.setForeground(PRIMARY);
    }
    //==============làm đẹp filter===============//  
    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        Date tuNgay = txtTuNgay.getDate();
        Date denNgay = txtDenNgay.getDate();
        System.out.println(denNgay);
        if (tuNgay.getTime()>denNgay.getTime() && tuNgay!=null && denNgay!=null)
        {
            JOptionPane.showMessageDialog(null, "Nhập sai ngày");
            txtTuNgay.requestFocus();
            return;
        }

        createBarChart(pnChart, tuNgay, denNgay);
        loadlistDocGiaSach(tuNgay, denNgay);

    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtTuNgay.setDate(null);
        txtDenNgay.setDate(null);

        initChartPanel();
        loadThongKe();
        loadlistDocGiaSach(null,null);
    }//GEN-LAST:event_btnResetActionPerformed

//    private void initTopPanel(){
//    pnTop.removeAll(); // xóa layout cũ của NetBeans
//
//    pnTop.setLayout(new GridLayout(1, 3, 10, 0));
//
//    pnTop.add(createItem("Tổng sách", "0"));
//    pnTop.add(createItem("Số phiếu mượn", "0"));
//    pnTop.add(createItem("Chưa xử lý phạt", "0"));
//
//    pnTop.revalidate();
//    pnTop.repaint();
//}
        private JPanel createItem(String title, String value) {
            JPanel panel = new JPanel();
            panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
            panel.setBackground(Color.WHITE);

            panel.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(new Color(220, 220, 220)),
                    BorderFactory.createEmptyBorder(15, 10, 15, 10)
            ));

            JLabel lblTitle = new JLabel(title);
            JLabel lblValue = new JLabel(value);

            lblTitle.setAlignmentX(Component.CENTER_ALIGNMENT);
            lblValue.setAlignmentX(Component.CENTER_ALIGNMENT);

            lblTitle.setFont(new Font("Segoe UI", Font.PLAIN, 14));
            lblTitle.setForeground(Color.GRAY);

            lblValue.setFont(new Font("Segoe UI", Font.BOLD, 26));
            lblValue.setForeground(PRIMARY);

            panel.add(lblTitle);
            panel.add(Box.createVerticalStrut(10));
            panel.add(lblValue);

            return panel;
        }

        private void initChartPanel() {
            pnChart.removeAll();
            pnChart.setLayout(new BorderLayout());

            Date tuNgay = null;
            Date denNgay = null;

            JPanel chartPanel = createBarChart(pnChart, tuNgay, denNgay); //hàm tạo chart

            pnChart.add(chartPanel, BorderLayout.CENTER);

            pnChart.revalidate();
            pnChart.repaint();
        }

        private void loadlistDocGiaSach(Date tungay, Date denngay) {
            Vector header = new Vector();
            header.add("Mã độc giả");
            header.add("Họ độc giả");
            header.add("Tên độc giả");
            header.add("SDT");
            header.add("Địa chỉ");
            header.add("Trạng thái");
            header.add("Số sách đã mượn");
            DocGiaBUS dgbus = new DocGiaBUS();
            PhieuMuonBUS pmbus = new PhieuMuonBUS();
            int daMuon;
            DefaultTableModel model = new DefaultTableModel(header, 0);
            for (DocGiaDTO docgia : DocGiaBUS.dsdg) {
                Vector now = new Vector();
                now.add(docgia.getMaDG());
                now.add(docgia.getHoDG());
                now.add(docgia.getTenDG());
                now.add(docgia.getSDT());
                now.add(docgia.getDiaChi());
                now.add(docgia.getTrangThai());
                now.add(demSoSachDaMuon(docgia.getMaDG(),tungay, denngay));
                model.addRow(now);
            }
            tableDocGiaSach.setModel(model);
            customize();
        }

    private int demSoSachDaMuon(String madg, Date tungay, Date denngay)
    {
        PhieuMuonDTO pmdto = new PhieuMuonDTO();
        int daMuon=0;
        for (PhieuMuonDTO pm : PhieuMuonBUS.dsPhieuMuon) {
                    if (pm.getMaDG().equals(madg)) {
                        if (denngay==null || tungay==null)
                        {
                            daMuon++;
                        }
                        else
                        {
                            if (pm.getNgayMuon().getTime() >= tungay.getTime() &&
                                pm.getNgayMuon().getTime() <= denngay.getTime())
                                    daMuon++;
                        }
                    }
                }
        return daMuon;
    }
    private JPanel createBarChart(JPanel panel, Date tuNgay, Date denNgay) {
        // Tạo dataset
        CTPhieuMuonBUS bus = new CTPhieuMuonBUS();
        ArrayList<CTPhieuMuonDTO> list = bus.top10sach(tuNgay, denNgay);
        SachBUS sachBus = new SachBUS();
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (CTPhieuMuonDTO dto : list) {
            String tenSach = sachBus.timTenSachTheoMa(dto.getMaSach());
            dataset.addValue(dto.getTongSoLuong(), "Số lượt mượn", tenSach);
        }

//        dataset.addValue(20, "", "Lão Hạc");
//        dataset.addValue(15, "Số lượt mượn", "Doraemon");
//        dataset.addValue(10, "Số lượt mượn", "Rừng Na Uy");
//        dataset.addValue(8, "Số lượt mượn", "Nhà giả kim");
//        dataset.addValue(5, "Số lượt mượn", "Đắc nhân tâm");
//        dataset.addValue(2, "Số lượt mượn", "Giáo trình Java cơ bản");
        JFreeChart barChart = ChartFactory.createBarChart(
                "Top sách mượn nhiều",
                "Tên sách",
                "Số lượt mượn",
                dataset
        );
//===================làm đẹp chart================//
        CategoryPlot plot = barChart.getCategoryPlot();

        plot.setBackgroundPaint(Color.WHITE);
        plot.setRangeGridlinePaint(new Color(220, 220, 220));

        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setSeriesPaint(0, PRIMARY);

        barChart.getTitle().setPaint(TEXT_DARK);
//===================làm đẹp chart================//

        // Đưa vào panel
        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new Dimension(800, 300));

        panel.removeAll();
        panel.setLayout(new BorderLayout());
        panel.add(chartPanel, BorderLayout.CENTER);
        panel.validate();
        return chartPanel;
    }

    private void loadThongKe() {
        int tongSach = sachBus.countSach();
        int dangMuon = pmBus.countDangMuon();
        int chuaXuLy = phatBus.countChuaXuLy();

        pnTop.removeAll();
        pnTop.setLayout(new GridLayout(1, 3, 10, 0));

        pnTop.add(createItem("Tổng sách", String.valueOf(tongSach)));
        pnTop.add(createItem("Số phiếu mượn", String.valueOf(dangMuon)));
        pnTop.add(createItem("Chưa xử lý", String.valueOf(chuaXuLy)));

        pnTop.revalidate();
        pnTop.repaint();
    }

    private void styleTable() {
        tableDocGiaSach.setRowHeight(28);
        tableDocGiaSach.setFont(new Font("Segoe UI", Font.PLAIN, 13));

        JTableHeader header = tableDocGiaSach.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 13));
        header.setBackground(PRIMARY);
        header.setForeground(Color.WHITE);

        tableDocGiaSach.setSelectionBackground(PRIMARY_LIGHT);
        tableDocGiaSach.setGridColor(new Color(230, 230, 230));
    }

    //Làm đẹp bảng
    private void customize() {
        tableDocGiaSach.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS); // Căn tự độngss

        tableDocGiaSach.getColumnModel().getColumn(0).setPreferredWidth(120);   // Mã dg
        tableDocGiaSach.getColumnModel().getColumn(1).setPreferredWidth(200);  // Họ dg
        tableDocGiaSach.getColumnModel().getColumn(2).setPreferredWidth(170);  // Tên dg
        tableDocGiaSach.getColumnModel().getColumn(3).setPreferredWidth(150);  // SDT
        tableDocGiaSach.getColumnModel().getColumn(4).setPreferredWidth(140);  // Địa chỉ 
        tableDocGiaSach.getColumnModel().getColumn(5).setPreferredWidth(120);   // Trạng thái
        tableDocGiaSach.getColumnModel().getColumn(6).setPreferredWidth(200);   // Số sách đã mượn

        tableDocGiaSach.setRowHeight(32);
        tableDocGiaSach.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        tableDocGiaSach.getTableHeader().setFont(
                new Font("Segoe UI", Font.BOLD, 16)
        );
        tableDocGiaSach.getTableHeader().setPreferredSize(
                new Dimension(tableDocGiaSach.getWidth(), 40)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnChart;
    private javax.swing.JPanel pnTop;
    private javax.swing.JPanel pnlFilter;
    private javax.swing.JTable tableDocGiaSach;
    private com.toedter.calendar.JDateChooser txtDenNgay;
    private com.toedter.calendar.JDateChooser txtTuNgay;
    // End of variables declaration//GEN-END:variables
}
